### ISSUE TITLE
Error with Apple News API: TOO_MANY_PREVIEW_ARTICLES

### ISSUE THREAD

**Issue by attackant** [alleyinteractive/apple-news#1088]
### Description of the bug

We are experiencing an issue with the Apple News API that is preventing us from publishing articles. When attempting to publish, we receive the following error message:

> There has been an error with the Apple News API: TOO_MANY_PREVIEW_ARTICLES

It appears that Apple News API is being sent too many draft articles causing the channel to exceed the maximum limit of 500 draft articles. We need to investigate how articles are being sent to Apple News in draft status and determine the best course of action to resolve this issue.

### Acceptance Criteria

- Investigate how articles are being sent to Apple News in draft status
- Identify any processes or integrations that may be causing an excessive number of draft articles
- Determine if there is a way to automatically clean up or remove old draft articles
- Provide recommendations on how to prevent this issue from occurring in the future
- Document findings and share with the team

### Steps To Reproduce

1. Attempt to publish a new article
2. Observe the error message: `There has been an error with the Apple News API: TOO_MANY_PREVIEW_ARTICLES`

### Additional Information

- The error message indicates that the maximum limit of 500 draft articles has been exceeded
- This issue is blocking our ability to publish new articles to Apple News
- Resolving this issue is high priority
- It has been [reported by other users as well](https://wordpress.org/support/topic/there-has-been-an-error-with-the-apple-news-api-too_many_preview_articles/)

**Comment by kevinfodness** [comment]
@attackant let me know what you figure out here - I suspect this is not an issue with the plugin itself, but with something else in a workflow (e.g., automatically configuring non-production environments to push articles as previews, which aren't subsequently being cleaned up via News Publisher). If the issue is indeed within this plugin and not within implementation code for one or more publisher sites, then we can discuss how to handle within this plugin and a timeline for release.

**Comment by attackant** [comment]
@manewc Did anything come out of the ticket you had on this issue?

**Comment by manewc** [comment]
The client's issue was more that they received an email from Apple stating they had too many draft posts in their account and they needed to take action to reduce the drafts. The issue was more that the drafts posts were showing as being updated frequently, which was possible although not probable. The result ended up being more on Apple's end:

> The timecode was refreshed recently due to a maintenance task on our end, during which we reprocessed old draft articles.

I don't believe they ever had an experience where they were blocked from publishing which sounds like the case expressed https://wordpress.org/support/topic/there-has-been-an-error-with-the-apple-news-api-too_many_preview_articles/.

In that ^ case I would be interested to know how many draft articles they actually have in their account and if reducing < 500 will correct the problem.

**Comment by attackant** [comment]
Closing this issue as it appears to have been an issue outside of the plugin itself and there have been no replies in 5 weeks from the WP.org poster.

**Comment by dennissellers** [comment]
I'm have the same problem at www.appleworld.today -- and have  had the issue for weeks.

**Comment by kevinfodness** [comment]
@dennissellers you will need to delete preview articles from iCloud News Publisher to get below the limit. The plugin does not publish preview articles to iCloud News Publisher by default - you have to check the box to publish an article as a preview. It's possible that you have a non-production environment that is configured to always publish articles as preview, and it has driven up the number of preview articles you have, but that behavior would be coming from code outside of this plugin.
