### ISSUE TITLE
Spike: evalutate how to make the Apple News Index page more performant

### ISSUE THREAD

**Issue by renatonascalves** [alleyinteractive/apple-news#1166]
### Description

In a large site, with +1m posts in Apple News, I noticed the Index Page is not very performant, taking almost 10s to build the page.

⚡ This one had only one post type.

![CleanShot 2024-09-12 at 12 36 11@2x](https://github.com/user-attachments/assets/b836b64f-8883-4697-a684-8c4973ca3004)

In another env, with +800k posts, it took 6s.

⚡ This one had three different post types.

![CleanShot 2024-09-12 at 12 33 09@2x](https://github.com/user-attachments/assets/cd59ea9d-f1b5-4f27-bf7d-6c20f20c8694)

### Use Case

I haven't dug into this as to why and what could be done. But I don't see the same slowness in similar List Table for the same post type and with the same number of posts.

**Comment by kevinfodness** [comment]
The default query on that page doesn't include taxonomy filters. Where is that `term_taxonomy_id` subquery coming from in your example? I suspect that something in your code is using the `apple_news_export_table_get_posts_args` filter to modify the default arguments for that list table, or is using a more generic query to modify certain types of queries in the admin.

ref: https://github.com/alleyinteractive/apple-news/blob/develop/admin/class-admin-apple-news-list-table.php#L341

Generally, this page is slow to load because it has to sync the status for each article in the list with Apple, which could be done in an async way to prevent initial page load times from being slow, but that's not tied to the performance of that query.

**Comment by renatonascalves** [comment]
The taxonomy filters are custom code, but not related to the slowness since I can replicate the behavior without them.

After some testing, it seems the cached (in the object cache) posts are _invalidated_ too quickly?!, so a request is not cached long enough to be used, forcing the query to be sent to mysql. This behavior is obvious here due to the size of the database.

**Comment by renatonascalves** [comment]
Closing it since it is not a code issue. 🪂
