### ISSUE TITLE
iFrame in post preventing publish

### ISSUE THREAD

**Issue by matfleaydaly** [alleyinteractive/apple-news#127]
G'day Guys,
I am running the iframe plugin on my website (https://wordpress.org/plugins/iframe/) and it seems that any of my posts that include this plugin will not publish due to an API error.
The API error is as follows: `[body] => {"errors":[{"code":"INVALID_DOCUMENT","keyPath":["root","components","[4]","URL"],"value":"null","message":"\"URL\" was <null> should be valid URL with one of [\"http\",\"https\"] scheme(s)"},{"code":"INVALID_DOCUMENT","keyPath":["root","components","[4]"],"message":"no components defined for role=embedwebvideo"}]}
    [response] => Array`
Is there any chance of some sort of fix for this that will allow the post to still be published?
Cheers!

**Comment by bcampeau** [comment]
Please provide the JSON file and a link to the post on your site that's causing this error. Thanks.

**Comment by matfleaydaly** [comment]
G'day Mate, Thanks for the reply!
Here is a link: http://thechute.mattsphotos.com.au/2016/03/29/good-friday-2016/
Attached is the JSON file.
Cheers!
[article-217.json.zip](https://github.com/alleyinteractive/apple-news/files/201640/article-217.json.zip)

**Comment by bcampeau** [comment]
If you used the News Preview tool to validate your JSON file, you'd see the following errors:

`Error: "URL" was <null> should be valid URL with one of ["http","https"] scheme(s)
document -> components -> [4] -> URL

Error: no components defined for role=embedwebvideo
document -> components -> [4]`

This seems to be occurring because your YouTube video URL is getting stripped out for an unknown reason. I'll have to look into this further to see if it's a bug with the plugin.

**Comment by bcampeau** [comment]
This is being evaluated for inclusion in the 1.0.8 release if it turns out to be related to the fix for #132
