### ISSUE TITLE
Remove duplicate featured image if it is also present in a post

### ISSUE THREAD

**Issue by kevinlisota** [alleyinteractive/apple-news#149]
When a featured image is not present on a post, your plugin grabs the first image in the post to use as the Apple News cover and then deletes it from the article body. We have the opposite need.

All of our articles have a featured image set on our site. It is a requirement of our site design. We use the featured image to display on archive pages, but we do not actually use the featured image on single post pages.

Sometimes that image isn't present at all in the article body. Other times it is inserted manually in the article body, often at the beginning of the article.

The result is that in Apple News the cover image is duplicated in the article body, sometimes immediately after a headline, which looks awkward.

I think the plugin should check for both scenarios:

1. If featured image (cover) is not set for a post, pull the first image from the article and remove it from the article (plugin already does this)
2. If featured image (cover) is set for a post, check to see if the featured image is present in the article body. If it is, remove it to prevent duplication of the image in Apple News.

**Comment by bcampeau** [comment]
This is something that we discussed thoroughly on our end and we decided not to do it. This is because some sites actually want that and it tends to be a more common use case. The featured image could occur again much further down than your scenario or as part of a gallery.

I'd suggest using one of the available filters in the plugin to modify the post body as you wish before pushing to Apple News.
