### ISSUE TITLE
Add Facebook Component

### ISSUE THREAD

**Issue by bcampeau** [alleyinteractive/apple-news#188]
https://developer.apple.com/library/prerelease/content/documentation/General/Conceptual/Apple_News_Format_Ref/FacebookPost.html#//apple_ref/doc/uid/TP40015408-CH106-SW1

**Comment by umbrella-kirill-starikov** [comment]
Hi There. I tested apple-news v1.2, Facebook posts with videos are not working for me. 
In newsPreview everything works perfect, but when I want to publish a post, I get the error

`There has been an error with the API: INVALID_DOCUMENT - Unable to find oembed resource for URI=https://www.facebook.com/stylecaster/videos/10153990641621012/ (keyPath components->3), INVALID_DOCUMENT - no components defined for role=facebook_post (keyPath components->3) `

My code from JSON is 
`{
"role":"facebook_post",
"URL":"https:\/\/www.facebook.com\/stylecaster\/videos\/10153990641621012\/"
}`

FYI: when I publish a post with FB embed without videos, there is no this error. 
Are you planning to add support for fb video? What period of time?

**Comment by bcampeau** [comment]
Can you please provide the entire JSON file either via [pastebin](http://pastebin.com/) or [gist](https://gist.github.com)?

**Comment by kevinfodness** [comment]
@umbrella-kirill-starikov Video URLs are not supported by Apple News. You can see the list of supported URL formats here: https://developer.apple.com/library/prerelease/content/documentation/General/Conceptual/Apple_News_Format_Ref/FacebookPost.html#//apple_ref/doc/uid/TP40015408-CH106-SW1

Since this is at the level of Apple News itself, there isn't anything we can do about adding support for Facebook video URLs at this time.

**Comment by umbrella-kirill-starikov** [comment]
@kevinfodness ah, thank you
