### ISSUE TITLE
Pre and Code Tags Not Supported

### ISSUE THREAD

**Issue by chriscoyier** [alleyinteractive/apple-news#222]
(More of a question than bug, feel free to close and point me in the right direction if possible.)

Apple News doesn't support `<pre>` and `<code>` tags apparently. 

This plugin knows that, and removes them.

<img width="930" alt="screen shot 2016-08-28 at 12 05 50 pm" src="https://cloud.githubusercontent.com/assets/69156/18035250/d4ea9f8e-6d17-11e6-881e-e5b184ff25c0.png">

This makes them not appear in the live Apple News articles, which can make for awkward reading. 

Could they be transformed into like... `<p style="white-space: pre; font-family: monospace;">` or something? So at least they look like code and aren't just stripped?

**Comment by bcampeau** [comment]
Chris,

You're right that `<pre>` and `<code>` aren't supported by Apple News. Your suggestion doesn't directly work either because inline CSS isn't parsed by the plugin. Apple News body components use markdown, which does support code formatting. However Apple's subset of markdown doesn't include it.

I've given this some thought and I think a hybrid of your suggestion and using markdown will be the right solution. Specifically, Apple's subset of markdown does include [inline text styles](https://developer.apple.com/library/ios/documentation/General/Conceptual/Apple_News_Format_Ref/Markdown.html). We could in theory then do the following:

Convert `<pre>` and `<code>` to paragraphs
Create an inline style that uses a monospaced font and wrap the entire content of that paragraph in it

Currently, we have the next four versions of the plugin on a well defined roadmap so I'm not sure when this can be worked on. It does seem like a great idea though. We're open to pull requests if this is something you're interested in contributing and we can help guide you to the right place to do it.

Thanks.

**Comment by chriscoyier** [comment]
I could likely give a pull request a shot. Any guidance as to what files it makes the most sense to put this code would be helpful!

**Comment by bcampeau** [comment]
I reached out to a couple other folks that *may* have a solution for this already. Once I hear back, I'll definitely provide some more details here.

**Comment by bcampeau** [comment]
After discussing, we agreed that there is no current accepted solution for this, which is actually kind of surprising! I'll post some notes in a bit on what I think a solution would look like.

**Comment by bcampeau** [comment]
So I've given this some thought, and I think the best way forward is to add a new `Component` class called `Code`. You can see other examples in https://github.com/alleyinteractive/apple-news/tree/master/includes/apple-exporter/components.

The anatomy of a `Component` class is that it has a few basic functions to determine how it matches content with a post and then how it creates JSON for Apple News. I think that `Quote` is a pretty good example for us here. The prerequisite functions are:

# `node_matches( $node )`: This determines what HTML element(s) are matched by this `Component` class. For your example, it would be `pre` and `code`.
# `build( $text )`: This receives the contents of the HTML node and returns the JSON for the `Component`. In your case, I actually think the contents would be more similar to the `Body` component (i.e. `'role' => 'body'`)

There are other functions you'll definitely want to use here too:
# `set_style()`: Returns the JSON for the `Component `style.
# `set_layout()`: Returns the JSON for the `Component` layout.

Furthermore, I think that in the spirit of other components, the following attributes should be customizable:
# background color
# font face
# font size
# line height

The new settings should probably live here: https://github.com/alleyinteractive/apple-news/blob/master/admin/settings/class-admin-apple-settings-section-formatting.php

Note the defaults for any new settings also need to get added here: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/class-settings.php

Let me know if you have any questions and we'd love to see this become part of the plugin!
