### ISSUE TITLE
apple_news_skip_push filter is not called for async publishing

### ISSUE THREAD

**Issue by fabn** [alleyinteractive/apple-news#254]
We used filter `apple_news_skip_push` to exclude certain articles from automatic publishing. However that filter seems to not be used if async publish is enabled, see 

https://github.com/alleyinteractive/apple-news/blob/508e27e4d27882f5ea1b41835f4bf5413bb325be/admin/apple-actions/index/class-push.php#L47-L62

**Comment by fabn** [comment]
An easy fix should be in #255.

**Comment by bcampeau** [comment]
That's not true, actually. When an async push happens, it still ends up in the `push()` method in class `Push` where is where that filter is located. That method is always called as it contains all the logic for pushing to Apple News.

I saw your pull request but that isn't something I'd merge as I don't think it's the correct fix or at the very least, it takes a brute force method to getting this to work rather than figuring out why this isn't working since the current filter is called for all pushes (or at least should be).

Please have another look at this and let us know what you find. Also, if you do end up introducing any new code, please be aware that all pull requests need to be accompanied by unit tests for consideration.

Thanks.

**Comment by fabn** [comment]
Ok, I assumed so because I've implemented the filter and if I use sync push filter is called and articles are correctly excluded, while if I use async publish, the very same article is not skipped and it is published on Apple News.

For what it worths production code is run on Wordpress VIP platform.

Feel free to close the linked PR.

**Comment by bcampeau** [comment]
Thanks, we support the plugin on VIP too.

I mean, it SHOULD be called but if in your experience, it's NOT being called, it should be debugged. If that's definitely the case and if you give us some more information, we're happy to help you look into it.

**Comment by fabn** [comment]
@bcampeau I found out that the issue was not in your code, but in another part of the skip logic.

So this is definitely a non issue.

Closing it, thanks for your assistance.
