### ISSUE TITLE
Video Being Skipped

### ISSUE THREAD

**Issue by AssyriaGameStudio** [alleyinteractive/apple-news#258]
Hi, so we're using a plugin to allow us to display videos responsivley / at the correct size when our site is viewed on mobile. This spits out the video in the following structure once formatted:

```
<div id="video-CzRgr0dxFI" class="arve-wrapper" data-arve-mode="normal" data-arve-provider="youtube" itemscope itemtype="http://schema.org/VideoObject">
<span class="arve-embed-container">
<meta itemprop="embedURL" content="https://www.youtube-nocookie.com/embed/CzRgr0dx_FI?iv_load_policy=3&amp;modestbranding=1&amp;rel=0&amp;autohide=1&amp;playsinline=1&amp;autoplay=0">
<iframe allowfullscreen class="arve-iframe fitvidsignore" frameborder="0" scrolling="no" src="https://www.youtube-nocookie.com/embed/CzRgr0dx_FI?iv_load_policy=3&#038;modestbranding=1&#038;rel=0&#038;autohide=1&#038;playsinline=1&#038;autoplay=0" width="480" height="270"></iframe>
</span>
</div>
```

Unfortunately it appears that the enclosing div / span is causing the Apple News plugin to skip the iframe / not process it. I was just wondering if it was possible to somehow make it ignore the enclosing tags and still process the video / iframe?

**Comment by bcampeau** [comment]
That might not be the issue. It could also be that it's not recognizing that URL format as a YouTube video. The plugin currently only supports YouTube and Vimeo in their standard embed formats. Also I'm not sure what the domain `www.youtube-nocookie.com` is. Is that really the URL to your video? 

I'd recommend not putting videos in an iframe since it's bad for responsive design in general. Consider switching to an [oEmbed](https://codex.wordpress.org/Embeds).
