### ISSUE TITLE
API errors for selected posts

### ISSUE THREAD

**Issue by atdr** [alleyinteractive/apple-news#338]
After a server move, I'm now getting *inconsistent* API errors when publishing / updating content.

Certain new posts work fine; the vast majority error with
```
There has been an error with the API: SERVER_ERROR
```

Old posts are also susceptible—some can be updated as expected but others also error with
```
There has been an error with the API: NOT_FOUND (keyPath articleId)
```

In a potentially related issue, [post transformation to Facebook Instant Articles is erroring on `<meta>` tags](https://github.com/Automattic/facebook-instant-articles-wp/issues/630) (though there are none in the post content itself).

I've tried updating the API connection settings to no avail.

---

**Version Info**

- Plugin version: 1.2.4
- WordPress version: 4.7.2–en_GB
- PHP version: 7.0.15

**Comment by kevinfodness** [comment]
Hi @atdr—

I believe your two issues are unrelated. For the first one, I would recommend looking into your server error logs and checking with your host, because it seems like a connectivity issue between your site and Apple's API.

Another possibility is this open pull request: https://github.com/alleyinteractive/apple-news/pull/337

You could try updating the API URL in `admin/apple-actions/class-api-action.php` to see if that gives you more consistent behavior. This update will likely make it into a future release.

**Comment by cjh357** [comment]
I'm working with @atdr on the project that gave the above issue.

`There has been an error with the API: SERVER_ERROR` seems to have been fixed for us by going to _Sections_ under the plugin's settings and changing the _Theme_ for _Main_ (the only one we use) from blank to _Default_.

We'll keep an eye on things to see whether the issue reoccurs.

**Comment by kevinfodness** [comment]
Thanks, @cjh357. I'll close this issue. If you have any additional trouble, please let us know.
