### ISSUE TITLE
Multiple thumbnails being created - uploads directory bloated!

### ISSUE THREAD

**Issue by vincepettit** [alleyinteractive/apple-news#339]
I've noticed that when an image is uploaded to Wordpress it now creates about 7 more versions of the same image, this appears to being created by this plugin.

- apple_news_ca_landscape_4_7 - 632x474
- apple_news_ca_landscape_4_0 - 536x402
- apple_news_ca_portrait_5_5	- 687x500
- apple_news_ca_portrait_4_7	- 414x500
- apple_news_ca_portrait_4_0	- 354x472
- apple_news_ca_square_4_7	- 550x500
- apple_news_ca_square_4_0	- 470x470

Are they **100%** necessary to be created for submission? and if so is there a way that after submission we can clear down the submitted images as we've seen our uploads directory starting to get bloated with different size versions of the same file.

**Comment by kevinfodness** [comment]
Hi @vincepettit—

Thanks for the feedback. Yes, those image sizes are required in order to submit cover art, which was added in version 1.2.3 and refined in version 1.2.4. Apple will reject submissions that contain cover art that is not at the proper aspect ratio, and these crop sizes ensure that the images are sent at exactly the correct dimensions.

You are correct that not every image size will be required for every submission, or even every post, but WordPress is configured to generate image crops at the time of upload and not on demand. Deleting these crops is not an option either, as users that have the remote images setting enabled will need to keep those images hosted on their domain in order to support the feed.

If you have a need to generate image crops on demand and offload the crops from your server, I would recommend looking into a product such as WordPress.com's Photon, which is available through Jetpack: https://jetpack.com/support/photon/

**Comment by kevinfodness** [comment]
Reopening this issue—we're getting additional feedback on this, and it might be a good idea to allow users to opt out of cover art so we aren't generating a bunch of extra crops for users that aren't interested in the feature.

**Comment by kevinfodness** [comment]
Specifically, we'll have Cover Art support off by default, which will mean that crops are off by default, and only enable the crops if users turn on support for Cover Art.

We are also getting reports from at least one user that these image sizes are affecting the output of `srcset` for images embedded on the front-end, which merits investigation and resolution.

**Comment by tylerwgreen** [comment]
I'm the user who reported the srcset issue. I am not seeing the apple news crops in the srcset of images embedded in the post. I am seeing them in other placements within the theme. This could be an issue with the theme and not necessarily the plugin. Thought I should clarify this.

**Comment by therevolver** [comment]
Is there any word on when this feature will be available? I don't use the cover option in my design and have it as inactive in my theme. That said I'm still getting a lot of extra images created that I don't need.

**Comment by kevinfodness** [comment]
@therevolver—we don't have a specific timeline on this enhancement. In the interim you should be able to use the `intermediate_image_sizes` filter at a high priority to remove the extra crops added by Publish to Apple News.

**Comment by jennafarr** [comment]
We are having this same issue with tons of images being generated with no use for Cover Art. Can you clarify the workaround with "intermediate_image_sizes"? Is this something we'd modify in the plugin or in our theme?

**Comment by therevolver** [comment]
This is the function we're using, it doesn't remove all of the sizes the plugin tries to create because some of our images aren't that big

function remove_plugin_image_sizes() {remove_image_size('apple_news_ca_landscape_5_5');remove_image_size('apple_news_ca_landscape_4_7');remove_image_size('apple_news_ca_landscape_4_0');remove_image_size('apple_news_ca_portrait_12_9');remove_image_size('apple_news_ca_portrait_9_7');remove_image_size('apple_news_ca_portrait_5_5');remove_image_size('apple_news_ca_portrait_4_7');remove_image_size('apple_news_ca_portrait_4_0');remove_image_size('apple_news_ca_square_9_7');remove_image_size('apple_news_ca_square_5_5');remove_image_size('apple_news_ca_square_4_7');remove_image_size('apple_news_ca_square_4_0');}

**Comment by jdiff** [comment]
To remove all of the extra image sized created by this plugin, 
first deactivate the plugin.

Then comment out the following lines:
	
```
		// Register custom image crops.
		$image_sizes = self::get_image_sizes();
		foreach ( $image_sizes as $name => $data ) {
			add_image_size( $name, $data['width'], $data['height'], true );
		}

```

under `public function action_init() `

in the file `admin/class-admin-apple-news.php`.

Then reactivate the plugin.
