### ISSUE TITLE
Improve handling of <figure> elements

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/apple-news#372]
Currently, `<figure>` elements are assumed to always contain images, but that isn't necessarily the case. Add some nuance to the parser to be able to handle `<figure>` elements that contain other types of content (code snippets, videos, flow content, etc).

**Comment by onpubcom** [comment]
Consider also other forms of markup that the WP post editor will generate for image `[caption]` embeds, for example when an image is linked to the full sized image and it has a markup structure like the following:
```
<figure>
  <a href="[...]">
    <img src="[...]">
  </a>
  <figcaption>[...]</figcaption>
</figure>
```
The `Image` `Component` class looks to be unable to parse the caption text from the above structure due to the link tag being present, so it looks like the `node_matches()` method in that component class needs some tweaks in order to detect this scenario, as what it currently detects with the above markup is only an inline image without caption, even though the caption markup is present.

Thanks for taking the time to write this plugin.

**Comment by kevinfodness** [comment]
@onpubcom the latest version of the plugin, v2.1.0, released today, fixes the caption issue. I'm going to close this issue, as we should really be handling other types of figure code in accordance with how they were inserted, rather than having a generic parser for figures.

**Comment by onpubcom** [comment]
Cool, thanks for the update and fix @kevinfodness , will try it out! -Corey
