### ISSUE TITLE
Revisions fail to update 

### ISSUE THREAD

**Issue by nomad-mystic** [alleyinteractive/apple-news#393]
Having some issues with getting updated(revisions) pushed to Apple News. Attached is the response, both the original created article and the revision. Looks like the body of the data is missing. Any insight would be much appreciated. Thanks Keith 
[7_5_2017_og_article.txt](https://github.com/alleyinteractive/apple-news/files/1126081/7_5_2017_og_article.txt)
[7_5_2017_revision_missing_key.txt](https://github.com/alleyinteractive/apple-news/files/1126082/7_5_2017_revision_missing_key.txt)

#

**Comment by bcampeau** [comment]
@nomad-mystic not exactly sure what you mean by "the body of the data is missing". If you mean you don't see the article JSON in the response in your file `7_5_2017_revision_missing_key.txt`, it's not missing. When an error occurs, only the error is returned and not the JSON you sent to Apple News for that article.

According to the error, the `revision` ID is missing from the `data` on your request meta. However, your debug file shows that it was actually present, so this is a bit confusing. This would look to be an API error rather than a plugin error based on the evidence I'm seeing here.

Have you reached out to Apple News support about this issue? They are familiar with the debug files the plugin generates and should be able to help you trace the request on their end.

Thanks.
