### ISSUE TITLE
Automatically publish to Apple News NOT Working !!

### ISSUE THREAD

**Issue by gkteck** [alleyinteractive/apple-news#414]
Hi,

Here is my setting in apple new, But when I publish articles on WordPress site, it is not publishing to apple news. I get a success message in the WordPress article publish page though.

Every time after publishing, I have to open the Apple new and manually publish it.
I am running on latest plugin version on **WordPress 4.5.3**
Automatically publish to Apple News when published in WordPress   **yes**
Automatically update in Apple News when updated in WordPress   **yes**
Automatically delete from Apple News when deleted in WordPress   **yes**
Asynchronously publish to Apple News  **no**

**Comment by kevinfodness** [comment]
Hi @gkteck—

Can you enable debug mode and attach the error log output, please? That will help us to determine what exactly is going on. For instructions, see: https://github.com/alleyinteractive/apple-news/wiki/configuration#developer-tools

You should also check the PHP error logs on your host, because if there is a PHP fatal error, it would prevent the post from publishing.

Also, although the plugin *should* work on WordPress 4.5.3, most of our testing is done on newer versions. Would it be possible to update to latest (4.8.1)?

**Comment by gkteck** [comment]
Hi ,

I have opened a related issue
https://github.com/alleyinteractive/apple-news/issues/420

The Root Cause of this issue is, the apple news plugin does not all roles other than admin to publish articles to apple news.

**Comment by kevinfodness** [comment]
I'm going to close this issue and reopen #420 as an enhancement request to allow modification of the role required for publishing via the admin.
