### ISSUE TITLE
User with Author Role not able to publish to Apple news

### ISSUE THREAD

**Issue by gkteck** [alleyinteractive/apple-news#420]
Looks like only users with Administrator role able to publish to apple news.

when users with author role try to publish, the news is not getting published.

Every time an admin needs to login --> Edit article --> Click update button to get published to apple news !!!

**Comment by dhanendrannewscorp** [comment]
@gkteck Apple News plugin requires minimum cap of `manage_options` to publish to Apple News. By default only admin will have this cap, if you would like to allow authors to publish to Apple News you can use `apple_news_publish_capability` filter to change the minimum cap to `edit_posts`.

Ref: https://github.com/alleyinteractive/apple-news/blob/master/admin/class-admin-apple-post-sync.php#L61

https://codex.wordpress.org/Roles_and_Capabilities#Author

**Comment by kevinfodness** [comment]
Thanks for providing the explanation, @dhanendrannewscorp.

**Comment by gkteck** [comment]
Hi @dhanendrannewscorp ,

Thanks for the update.
But I am not sure on how to proceed.

Can you please list the steps to enable authors to publish to Apple News ?
I hope this will help other users who are facing the same issue.

@kevinfodness ,
Is there any plan to enable authors to publish to Apple News ?

**Comment by kevinfodness** [comment]
@gkteck—The plugin allows you to customize the user capability required for publishing via the filter that @dhanendrannewscorp mentioned. You will need to implement this filter in your theme. I would recommend reading about filter hooks here: https://codex.wordpress.org/Plugin_API

Once you are familiar with the concept of how to utilize filters in your theme, you will need to use the `apple_news_publish_capability` filter and return a capability that authors have in order to allow authors to publish to Apple News.

I hope this helps!

**Comment by gkteck** [comment]
Hi @kevinfodness ,

I have added User Role editor plugin --> Using it  Added new capability  apple_news_publish_capability and added this capability to Author Role.

But still the news is not getting published.

**Comment by dhanendrannewscorp** [comment]
@gkteck that's not the right way to do it. You need to hook your function to `apple_news_publish_capability` filter which should return `edit_posts` cap.

Something like below;
```
add_filter( 'apple_news_publish_capability', function() {
    return 'edit_posts';
} );
```

As @kevinfodness mentioned please refer the WordPress documentation https://codex.wordpress.org/Plugin_API and specifically https://developer.wordpress.org/reference/functions/add_filter/

**Comment by gkteck** [comment]
Looks like this is NOT a simple change.
A lot of site admins will find this very difficult, My request is to add this as an option to future plugin update.

**Comment by kevinfodness** [comment]
OK, I'll reopen this as an enhancement request to add role customization via the Settings panel.

**Comment by gkteck** [comment]
@kevinfodness  when can we expect this enhancement to be available?

**Comment by kevinfodness** [comment]
Hi @gkteck—

I don't have a specific timeline for the next release, but there are a few issues we'd like to squash relatively soon.

**Comment by kevinfodness** [comment]
Hi @jnsprngs —

This issue is on our roadmap for version 1.4.0, which is under active development. Although I can't promise a specific release date, I would imagine that it would be sometime within the next two months. The plan for this is to separate the role checks for publishing and administration of the plugin to better align with native roles in WordPress, as you suggest.

**Comment by gkteck** [comment]
@kevinfodness  what is the tentative release date for 1.4.0?

**Comment by kevinfodness** [comment]
@gkteck —

We don't have a tentative release date, but it's close to being done. If you'd like to help with beta testing, you can pull the latest master from here and let me know if you run into any problems.
