### ISSUE TITLE
Display currently active theme in post editor

### ISSUE THREAD

**Issue by jonesmatthew** [alleyinteractive/apple-news#454]
Is the currently active theme stored somewhere in such a way as to make it possible to display it on the post editor page? In scenarios where there are multiple themes, it would be useful to have a clear indication of which one is active. Thanks!

**Comment by kevinfodness** [comment]
This is actually rather complicated, as there are now automation rules that determine which theme will be used for a particular article based on category selection etc. These rules are in the Automation view. Rather than trying to duplicate that logic in JavaScript as the user makes changes to categories to show on the post edit screen, we'll leave that configuration to the Automation screen.
