### ISSUE TITLE
Tablepress shortcode not working on submit

### ISSUE THREAD

**Issue by vincepettit** [alleyinteractive/apple-news#534]
We use tablepress for our tables on our website but when the articles are pushed through to Apple News via the plugin it just has the shortcode in the article. What can be done to make sure it shows the table rather than the shortcode?

**Comment by kevinfodness** [comment]
Hi @vincepettit — This is the problem right here: https://github.com/TobiasBg/TablePress/blob/master/classes/class-tablepress.php#L148-L155

Since the TablePress plugin considers shortcode processing to be a "frontend" task, it never loads the file that is responsible for translating the shortcode. You could try filtering `apple_news_exporter_content` and invoking the TablePress shortcode filter yourself, or you could raise an issue with the TablePress maintainer, since this seems like a case that would affect more than just this plugin.

ref: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#adminapple-actionsindexclass-exportphp-1
