### ISSUE TITLE
Schedule old posts to publish

### ISSUE THREAD

**Issue by Haileymurph** [alleyinteractive/apple-news#550]
Hello! I have a backlog of about 500 posts that I would like to publish over time to Apple News. Is there a way to schedule these posts to push to apple news a few each day? They've already been published in Wordpress but i dont want to flood Apple News with 500 posts in 1 day

Part 2: Bulk publish does not work for me, is there a fix? If I try to bulk publish multiple posts it just brings me back to the home page of wordpress

**Comment by kevinfodness** [comment]
1. There is no way to do this within the plugin at the present time, but you could write a function using WordPress cron to check for posts that haven't yet published, and then schedule publish actions for them using the async system built into the plugin: https://github.com/alleyinteractive/apple-news/blob/master/admin/apple-actions/index/class-push.php#L82

You would need to have async publishing turned on within settings in order to leverage this approach. I would also strongly recommend testing this extensively in small batches before rolling it out to your production site in full force.

**Comment by kevinfodness** [comment]
2. Can you list the steps you are using when attempting to bulk publish so I can try to reproduce?
