### ISSUE TITLE
Changing API details?

### ISSUE THREAD

**Issue by getdujio** [alleyinteractive/apple-news#574]
Howdy, apologies if ive missed this looking through github but can't find a way to purge the old API settings and replace with new ones.

In a nutshell my AN Channel was accidentally deleted by Apple. I have created a new channel which of course have different API credentials. I am getting the forbidden error when trying to publish existing content to the new channel after replacing the API details. I have tried removing the plugin and re installing but it doesn't seem to do anything.

Any advice?

**Comment by kevinfodness** [comment]
We have an open issue to address changing credentials here: #438 . In the interim you could use phpMyAdmin or similar to remove the keys from the wp_options table, which are prefixed with `apple_news_`.

**Comment by chartier** [comment]
Has there been any movement on this? I am in the predicament where, because of a goofup on Apple's part, I had to create a new, separate Apple News channel. But our site is running on a WordPress.com business plan, and we cannot actually access the PhpMyAdmin to fix the credentials ourselves.

I asked their support to see if they could completely reset the plugin and wipe those records from our db, but this tier of support apparently doesn't have that ability. As far as I can tell, we're stuck now. 😔

**Comment by koconder** [comment]
Surley we can add a hidden admin menu item to clear plugin settings and reset with a warning?
