### ISSUE TITLE
Publish to Apple News conflict with Smart Ad Server

### ISSUE THREAD

**Issue by rossfuru** [alleyinteractive/apple-news#578]
Hi,

Activating your plug-in inhibits our ads from being served to our site from Smart Ad Server.

**Comment by kevinfodness** [comment]
In what way? Can you link me to an example? Is this on the front-end of your site? Are you seeing an error?

This plugin does not affect the display of your articles on the web, it only sends them to Apple when requested. Apple uses its own ad servers for content on Apple News itself, so if the issue is that you can't serve ads from Smart Ad Server via Apple News, that is expected behavior.
