### ISSUE TITLE
Wordpress Code Showing in Article after posting

### ISSUE THREAD

**Issue by T4Viral** [alleyinteractive/apple-news#580]
I have noticed that my articles are showing Wordpress code when publishing.  Any ideas about how to resolve this issue?!

 Apple News Page is:  Montana.BEER if you wanted to see the errors

An example is: 
[et_pb_section bb_built="1" _builder_version="3.0.47" custom_padding="34px|0px|40px|0px"][et_pb_row custom_padding="0|0px|0|0px" _builder_version="3.0.47" background_size="initial" background_position="top_left" background_repeat="repeat"][et_pb_column type="4_4"][et_pb_text _builder_version="3.0.106" background_layout="light"] The Billings brewery scene is host to a number of Montana’s top breweries, and their “Walkable Brewery District” --> rest of article text

There is again more code at the conclusion of the article:  
[/et_pb_text][et_pb_gallery gallery_ids=”945,942,946,952,944,943″ fullwidth=”off” _builder_version=”3.0.106″ pagination_font_size_tablet=”51″ pagination_line_height_tablet=”2″ show_title_and_caption=”off” show_pagination=”on” orientation=”portrait” zoom_icon_color=”#00a8ff” hover_overlay_color=”rgba(255,255,255,0.9)” background_layout=”light” animation_style=”fold” posts_number=”6″ /][/et_pb_column][/et_pb_row][/et_pb_section]

Thanks for any help resolving!

**Comment by kevinfodness** [comment]
This seems to be an issue with a plugin that is providing support for shortcodes but is not being hooked into `the_content` filter. We have seen this sometimes when plugins try to be smart about when they register support for their shortcodes and don't invoke support in an admin context, which is required in order for Publish to Apple News to see the content and transform it. You will need to use one of our filters, most likely `apple_news_exporter_content_pre`, to transform these shortcodes to proper markup so that this plugin can transform the HTML: https://github.com/alleyinteractive/apple-news/wiki/Action-and-Filter-Hooks#adminapple-actionsindexclass-exportphp-1

**Comment by T4Viral** [comment]
@kevinfodness Thank you for the reply.  Where would I paste this code?

**Comment by kevinfodness** [comment]
We usually recommend pastebin.com, but any similar service would be fine.

**Comment by T4Viral** [comment]
Thanks for the info @kevinfodness 

Where should I paste the code generated from pastebin.com ? (sorry for the Noob question)

**Comment by kevinfodness** [comment]
You should be able to get a pastebin.com link to the content you copied, and you can put the link here as a comment.
