### ISSUE TITLE
Timeouts on pushes

### ISSUE THREAD

**Issue by paulgibbs** [alleyinteractive/apple-news#59]
Have you seen the article push to Apple timeout? e.g. "Operation timed out after 30001 milliseconds with 0 bytes received".

Obviously could have several causes (Apple, size of the article + assets being sent, etc), but I was wondering what you thought of automatically re-pushing failed submissions due to timeout? (on a cron, for example) or had other thoughts.

**Comment by bcampeau** [comment]
Resubmitting failed jobs is pointless because if your PHP max execution time is capped at 30 seconds, you're just going to be in an endless loop resubmitting posts that will never transmit. Because Apple News requires all images to be sent with the content in a single request, many posts will take in excess of 30 seconds especially image heavy content like slideshows.

In order to combat this, we've added some hooks and options to the plugin to allow you to work around this within your environment as appropriate. For example, on WordPress VIP, we use the asynchronous publishing option which automatically offloads the action to a single scheduled event. On VIP this then automatically goes to the jobs system which allows execution times up to 12 hours.

However, we don't automatically adjust the timeout on the post request as we leave this at the developer's discretion. The `timeout` by default is 30 seconds and can be adjusted using this filter: https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-push-api/request/class-request.php#L95

I hope that answers your questions.

**Comment by paulgibbs** [comment]
We have seen this problem on VIP, though I'm going to go and check if async is enabled or not.

**Comment by bcampeau** [comment]
Yeah but you do need to also filter the `timeout` in your theme as described above.

**Comment by paulgibbs** [comment]
ah ok

**Comment by bcampeau** [comment]
Going to mark this resolved. Also Apple is now processing images asynchronously on their end.
