### ISSUE TITLE
Generic Error when publishing

### ISSUE THREAD

**Issue by motrolix** [alleyinteractive/apple-news#601]
I'm getting this error when attempting to publish an article using this plugin: There has been an error with the API: There has been an error with your request: select/poll returned error.

I've changed the API keys twice, there's nothing in the php error log, and the debug email doesn't give any info either:

API Response:
WP_Error Object
(
   [errors] => Array
       (
           [http_request_failed] => Array
               (
                   [0] => select/poll returned error
               )

       )

   [error_data] => Array
       (
       )

)

Request Meta:

Array
(
   [data] => Array
       (
           [isPreview] => 
           [isHidden] => 
           [isSponsored] => 
       )

)

**Comment by kevinfodness** [comment]
This is a new one. It's not an Apple specific error, it's actually coming from cURL. Some of my search hits pointed to large files, so you could try turning on the Remote Images setting rather than trying to bundle and send the images. Other suggestions involved the number of request threads that exist concurrently, but I wouldn't imagine that would be a problem because it's sending the articles one at a time. My only other suggestion is to see if there are other processes on the server that are running cURL operations at the same time that you get this error.
