### ISSUE TITLE
There has been an error with the API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [bundle://ir]

### ISSUE THREAD

**Issue by audiogeek11** [alleyinteractive/apple-news#625]
'some' of my articles (around 50%) yielded this error. The images have filenames. The images are generally PNGs, but other articles with PNGs have updated successfully, what else could this be ?

**Comment by EM-MiguelRosas** [comment]
same error with svg image files, tried to remove them from the content using hook 'apple_news_exporter_content_pre' but failed to publish the post.

**Comment by kevinfodness** [comment]
Can you try setting Remote Images to "Yes"?

**Comment by EM-MiguelRosas** [comment]
can't, we're using a CDN and the way we're setup the plugin would not be pointing to our cdn servers.


I used the 'apple_news_generate_json' hook instead to remove the SVG images from the array within the components so I could remove it before the json is generated, that worked out ok for me.

**Comment by EM-MiguelRosas** [comment]
now I'm getting erros related to empty PNG images and JPG.

There has been an error with the API: The attachment CEB6DE41-C670-4062-AE60-E86B6090B73A-e1563758808981.png could not be included in the request because it was empty.

There has been an error with the API: FAILED_TO_PARSE_IMAGE - Failed to parse image with URI [bundle://F9B015FA-0F8D-46BE-8C52-3CD7EF650BCD-e1563765639725.png].

**Comment by kevinfodness** [comment]
It sounds like the plugin isn't able to download the content of your images, and therefore isn't able to bundle them.

I would recommend using a filter to point your images to the CDN and set Remote Images to Yes and have the images for Apple News serve up via your CDN.
