### ISSUE TITLE
Publishing API Error

### ISSUE THREAD

**Issue by getdujio** [alleyinteractive/apple-news#654]
Hello, 

When trying to submit an article I'm getting the following error

There has been an error with the API:
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->3->components->3->text)
INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->3->components->9->text)

my post just is text with two images so not sure what's happening, some others are publishing ok. My channel isn't live yet - just posting to news publisher for review. My plugin was previously setup to a different news channel and I changed the api settings to connect to the new one (if that makes any difference)

Here I have pasted the full API Response: https://pastebin.com/dy357AcX

**Comment by jwcounts** [comment]
I was experiencing the same error on my site, and I noticed something similar between our articles. In the JSON in the Pastebin that contains your actual article, components 3 and 9 are both empty paragraph tags.

<img width="706" alt="Screen Shot 2019-08-04 at 12 14 21 AM" src="https://user-images.githubusercontent.com/713850/62419742-5a959400-b64d-11e9-9e14-f2a6921b3e60.png">

I had 2 similar instances in my article (paragraph tags with non-breaking spaces in them), and removing them allowed the article to be pushed to Apple News.

I haven't looked at the code of the plugin in question, but I'm assuming there must be a way to check for empty text fields and skip them or something, especially since the Wordpress editor seems to love adding empty <p> tags into posts.

**Comment by kevinfodness** [comment]
We just released version 2 of the plugin. Can you test and see if the error persists in the new version? If so, I'll label it a bug and we will address in a future version.

**Comment by jwcounts** [comment]
Well, yes and no.  If I try to upload an article with a <p> containing only a normal space or &nbsp, then it fails to upload to Apple News (Example)[https://uofh-my.sharepoint.com/:i:/g/personal/jwcounts_cougarnet_uh_edu/Ean_rWbNwFFKnYd6WYKwjmsBkK5hr8bHhJP3Mem55bwgAA?e=596ua7]

However, if I remove the space and leave the <p></p>, it publishes successfully. (Example)[https://uofh-my.sharepoint.com/:i:/g/personal/jwcounts_cougarnet_uh_edu/EUMgjLavkndFv5V5x5fRV-UBWyE1DkGhlEjaZ1BO18mbEA?e=X5C4Cm]

**Comment by JenPen76** [comment]
This is still an issue as described by jwcounts. I see the same issue.

**Comment by kevinfodness** [comment]
Consolidating discussion of this issue in #707.
