### ISSUE TITLE
How to alter component's `style` property, not `text style`?

### ISSUE THREAD

**Issue by dashaluna** [alleyinteractive/apple-news#66]
I've been looking to add a border to a quote component.

According [to docs](https://developer.apple.com/library/ios/documentation/General/Conceptual/Apple_News_Format_Ref/Border.html#//apple_ref/doc/uid/TP40015408-CH55-SW1), the border is added to `ComponentStyle` property, not to confuse with `ComponentTextStyle` - which is different thing.

I've looked around code and couldn't find any filters that would allow me to alter component's `ComponentStyle`. Have I missed it?

For example, `Cover` component adds `style` aka `ComponentStyle` property in the `build()` function, but there are filters to alter it? Here is the [code reference](https://github.com/alleyinteractive/apple-news/blob/master/includes/apple-exporter/components/class-cover.php#L33).

I couldn't find a builder class for `ComponentStyle` similar to `ComponentTextStyle` - that would be super handy!

Is there other way I can alter `style` property to add a border?

**Comment by mattheu** [comment]
Short term - I think its OK to set the style directly on `$this->json` from the component class. 

However it would be neat to support `register_component_style` as well as the existing `register_layout` and `register_style`

Is this what you mean @dashaluna

**Comment by dashaluna** [comment]
@mattheu - pretty much.

At the moment I'm overwriting the native class with my own and adding `style` directly on `$this->json` from the component class. However, ideally I don't wanna do it, in case there will be some updates in the future to the native class. Hope that makes sense.

**Comment by bcampeau** [comment]
I'm about to embark on some major plugin updates, so I will consider how this can be integrated. Part of it is the integration of new components.

**Comment by dashaluna** [comment]
Sounds good! Thank you for consideration :+1:

**Comment by bcampeau** [comment]
The reason we don't have a `class-component-styles.php` that's analogous to `class-component-text-styles.php` is because they function a bit differently. Text styles can be defined at the top of the document and referenced later in each component using an identifier. That's why we made a filter for the array has all the text styles.

Styles however need to be assigned directly to each component, so there isn't one global place where they all exist. Also, in the built-in format we're using for Apple News in the plugin, not all components even have style declarations because we're fine with using the default styles there.

What I think makes the most sense here is to provide a filter for the JSON output for each individual component so you can at least edit the JSON in a more targeted fashion rather than having to use `apple_news_get_json` and parse the entire document.

I'll have an update soon.
