### ISSUE TITLE
Error status `"code":"ONLY_PREVIEW_ALLOWED"`with latest updates

### ISSUE THREAD

**Issue by brookenf** [alleyinteractive/apple-news#672]
The plugin for Apple News was working fine over the past month, but recently it broke. We were using `2.0.2` with the Classic Editor set to Auto-publish, and then rolled back to `1.4.3` (because of another issue saying that fixed the issue of auto-publishing), but I'm still receiving that error.

**Comment by jomurgel** [comment]
This may be related to #616 which points to a cause being potentially unapproved channel details.

**Comment by jomurgel** [comment]
Referencing the note in #616 from @brookenf. An update in 2.0.2 may resolve issues with auto-publishing on environments like where a mix of Gutenberg and Classic posts are present, which could be causing the error mentioned.

May be related to #669. Will keep open pending confirmation of a fix.

**Comment by brookenf** [comment]
@jomurgel We were previously on `2.0.2` when the issue first arose. Thank you for looking into this.

**Comment by zml440** [comment]
@brookenf Hi. I am new to coding/API in general but have some (very limited) knowledge. I have a confirmed account w/ Apple News and am able to publish to the channel using Hubspot via an RSS feed, so I know the issue is not on Apple's end. Our business is switching over to WP from Hubspot so I am trying to move all blog to WP as we transition.

I have double-checked that all of my API info was entered correctly into the WP plugin settings and still having issue as you all have experienced. I tried rolling back to 1.4.3 and am still getting the same error. Is there something I need to do in specific besides just trying to "publish" thru 1.4.3 plugin? I am not trying to use autopublish but I can't get anything to post even manually. 

Wondering if I am missing additional steps I need to take (e.g., JSON edits, adding some type of WP RSS feed to Apple News account settings, etc.)

Thanks so much! Sorry for the stupid question.

**Comment by brookenf** [comment]
@zml440 Sorry I can't be more helpful on the issue. I did not set up the Apple News plugin nor did the configurations, I am just a web developer for my company and have been asked to look into this issue. 

An issue first started over a month ago where images weren't being sent to Apple News, and then last week morphed into the issue we have right now of the error `ONLY_PREVIEW_ALLOWED`. THis issue is still plaguing us and I've both rolled back to `1.4.3` and re-updated to `2.0.2`, turned off autopublish and back on, but the issue persists. I am unfortunately unable to help you any further with this issue.

**Comment by kevinfodness** [comment]
Hi all - 

The `ONLY_PREVIEW_ALLOWED` message is coming from Apple's API, not from the plugin itself, so Apple is telling you that your channel is not allowed to receive published articles. You will need to follow up with Apple about this. Apple needs to approve your channel for publishing from the CMS, which involves receiving some sample articles exported from the CMS. It's possible that it could be approved for RSS publishing but *not* CMS publishing via the plugin, so following up with Apple's support is necessary here.
