### ISSUE TITLE
This story isn’t available in Apple News.

### ISSUE THREAD

**Issue by firmanpolyrific** [alleyinteractive/apple-news#684]
Hi, I'm still a newbie about apple news.

I'd like to know if we can use this plugin to publish an article to apple news from local environment?

I tried to publish an article from my wp site on my local, on the plugin page, it says PROCESSING then LIVE, but when I accessed the URL of my news (https://apple.news/AbGrn7f2hTd-qgr1-JNtluA), it says not available

does anyone have some quick getting started docs about how to use this plugin for development?

**Comment by jomurgel** [comment]
@firmanpolyrific you won't be able to publish directly from a local environment which is an issue of access by Apple to your local machine in order to publish.

If you're looking to preview/review what articles will look like before publishing from a live environment, I can suggest checking out the [News Preview](https://developer.apple.com/news-preview/) app from Apple in order to do so. The [News Publisher](https://developer.apple.com/news-publisher/) docs will also help.

The [Wiki](https://github.com/alleyinteractive/apple-news/wiki) is available to help get started with plugin development, most notably the [Action and Filter Hooks](https://github.com/alleyinteractive/apple-news/wiki/action-and-filter-hooks) section might be beneficial to you.
