### ISSUE TITLE
Version 2.0.3 Error - Allowed memory size of 268435456 bytes exhausted (tried to allocate 104487160 bytes)

### ISSUE THREAD

**Issue by Anthony-Joel** [alleyinteractive/apple-news#698]
I just published a page on my Wordpress site and got an email about the error which caused my admin page to shut down. I entered Recovery mode to disable Apple News which then allowed me to log back in to my admin page. I then enabled Apple News and manually published the article but had the same results. 

Error Details
=============
An error of type E_ERROR was caused in line 371 of the file /public_html/wp-content/plugins/publish-to-apple-news/includes/apple-push-api/request/class-request.php. Error message: Allowed memory size of 268435456 bytes exhausted (tried to allocate 104487160 bytes)

**Comment by Anthony-Joel** [comment]
Checking in to see if this issue has been reviewed. Is this something I can resolve without having to wait for an update? I have not been able to publish to Apple news for 8 weeks.

**Comment by kevinfodness** [comment]
This isn't something we've experienced with the plugin itself. It seems like one of two things is happening - either your theme or another plugin is allocating too much memory, or there is an infinite loop in action or filter hooks. What I would recommend is, in a test environment, disabling all plugins other than Publish to Apple News and seeing if you can recreate the error, and switching themes to one of the default ones (e.g., Twenty Twenty) and trying the same thing. That would help to identify whether the problem is with a plugin or your theme. If the error still occurs with just the Publish to Apple News plugin active and one of the default WordPress themes, then you should paste your post content here and we can try to reproduce on our end.

Thanks.

**Comment by Anthony-Joel** [comment]
Thanks. Will give your suggestion a try and report back.
