### ISSUE TITLE
Image captions being generated as body components

### ISSUE THREAD

**Issue by joshdarby** [alleyinteractive/apple-news#708]
On one of our member sites, all images with captions are having their captions being generated into the JSON as `body` components, regardless of whether or not the editor is classic or Gutenberg. 

I've written a function that fires on the `apple_news_generate_json` filter that basically gathers all images attached to a post, finds their captions, and if the caption matches a `body` component, it switches that component to `caption`. This fix works for _some_ articles, but not all, even though we're unable to find a distinguishing factor as to why it works for some but not others.

One other notable thing that's happening is that when trying to publish a post using the classic editor, we receive this error:
```
The following components are unsupported by Apple News and were removed:
img
```

An example image that's used when that error appears:
```
[caption id="attachment_331048" align="alignnone" width="771"]<a href="https://myurl.test/wp-content/uploads/2020/02/MG_4789.jpg"><img class="size-full wp-image-331048" src="https://myurl.test/wp-content/uploads/2020/02/MG_4789-1170x780.jpg" alt="" width="771" height="514" /></a> Gov. Tate Reeves delivers his first State of the State Address at the State Capitol Monday, January 27, 2020.[/caption]
```

I see a fix has been merged for #307, but that's for `figcaption` elements.

**Comment by kevinfodness** [comment]
This should be fixed in the latest version, released today (v2.1.0). Please let me know if you continue to experience an issue on the latest version.

**Comment by StevenCombes** [comment]
Unfortunately I'm having the same issue as @joshdarby has described here, with plugin version 2.2.0, and WordPress version 5.8.

Captions of images that are added to a post via the Add Media button in the WordPress editor are being generated into the JSON as body components.

Here's the plain text in the WordPress editor: https://pastebin.com/XHeUqp8f
Here's the JSON output of the Apple News article: https://pastebin.com/R2k8vKbz

Any help on troubleshooting the issue and getting proper image caption styling in place would be greatly appreciated.

**Comment by okadots** [comment]
@kevinfodness  I am also having this issue with 2.2.0 and Wp 5.8.  All of our image captions are being generated as body components.

**Comment by okadots** [comment]
@StevenCombes after some digging around, we discovered that HTML5 support for captions needs to be enabled for the plugin to accurately parse and convert the captions to actual captions. We added this line to `functions.php` and now the captions are being rendered properly as captions instead of paragraphs. (I should also note that we are _not_ using Gutenberg, this fix has only been tested with the old classic editor)

`add_theme_support( 'html5', array( 'caption' ) );`

**Comment by StevenCombes** [comment]
@okadots I can confirm that adding the line you provided to functions works! I truly appreciate the update! I am also using Classic Editor.

**Comment by kevinfodness** [comment]
Thanks @okadots - you're right, HTML5 support for captions needs to be enabled in order for image captions to work. Otherwise, WordPress just inserts them as a paragraph below the image, and our HTML matching isn't able to detect that signature in order to determine that the caption belongs to the image - essentially, there isn't a way to distinguish the caption from any other paragraph which might be below the image. I'll make sure that information gets added to the wiki.
