### ISSUE TITLE
There has been an error with the API: INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->19->text)

### ISSUE THREAD

**Issue by adamantski-birder** [alleyinteractive/apple-news#718]
Anyone know how to fix this? Sorry I'm new to GitHub

**Comment by BruceInLouisville** [comment]
I keep having the same problem. Have looked online in multiple places for a fix.

Someone said non-breaking space would cause it. Checked for those.

Someone said a space at the end of the article would cause it. Checked for those.

Since the first report of this was 2016, it seems to me that it should have been fixed by now -- or at least, some guidance provided as to what is causing it and how to prevent it.

Thoughts?

**Comment by kevinfodness** [comment]
Consolidating discussion of this in #707
