### ISSUE TITLE
There has been an error with the API: WRONG_SIGNATUR

### ISSUE THREAD

**Issue by BritishLinkz** [alleyinteractive/apple-news#719]
i am Frustrated to the max with trying to get this connected, i even changed the end point to https://u48r14.digitalhub.com as suggested in an earlier post.

Is anyone else experiencing this issue?

**Comment by torchpublishing** [comment]
You're not alone, we're having the same error when trying to publish. We've just established a new channel and want to upload the three sample articles but we get the wrong_signature error every time we try to post.
I'd love if someone could offer an explanation of where the problem may be. We have written to Apple News support but from past experience I'm not really expecting much assistance.

**Comment by kevinfodness** [comment]
That message comes directly from Apple's servers. The explanation of that error on the error codes page (https://developer.apple.com/documentation/apple_news/code) is:

```
The signature field given by the client did not match the signature computed by the server.
```

We compute the signature here: https://github.com/alleyinteractive/apple-news/blob/develop/includes/apple-push-api/request/class-request.php#L365-L379

The signature is composed of several elements, but most importantly, the secret key and *the current time*. If the secret key is entered incorrectly in the Settings page in WordPress, that could cause this error, although the most common scenario in which this error occurs is if the *time on your server is incorrect*. It is often the case that server time drifts slightly and needs to be periodically synchronized with another server using `ntp` or a similar tool. So the first place I would check is the secret key, and the second is to reach out to your hosting company and ensure that the time on the server is correct.

**Comment by torchpublishing** [comment]
Hi Kevin, many thanks for the response. 
I have triple checked the secret key is correct so I'm certain that's not the issue. As far as the time is concerned, we host the site here on our own server (it's a current model Mac running Mojave). The time is set automatically using time.asia.apple.com and our time zone is set correctly to Sydney Australia.
For the sake of the exercise I switched the server to Apple's US time server and changed our server settings to US  format (just in case the plugin was looking for a US formatted date). Still no luck - getting the same error.
I've updated the plugin to the version which was just released. I have re-entered the Channel ID, Key ID and Secret Key. 
I've tried with multiple browsers just in case there was something odd going on with Safari (the version I'm using from Sierra doesn't appear to properly save changes made in the plugin settings).
Later today I will see if I can generate another Secret and try again but at this stage I'm at a dead end and not sure what to try next.

**Comment by kevinfodness** [comment]
Here's what I would try. Open https://www.time.gov/ in a browser, which will show you the current time in the different timezones in the US. If you're set to a timezone in Asia, that's fine, because what you primarily want to pay attention to here are the minutes and seconds.

Then, open a terminal window and run `date` on your Mac server. It will give you the current date/time on your system. You want to compare the minutes and seconds of the time when you run that command against the minutes and seconds on the time.gov site. I don't specifically recall the threshold at which Apple's systems throw an error, but I think it's only a few seconds, so if you're noticing that the minutes aren't exact or the seconds are more than, say, 3s off, you have a time problem.

For the secret key, you may want to try typing it into the field directly to ensure you aren't copying invisible extra characters like spaces, etc. My guess is that it's the time, but best to be sure.

**Comment by kevinfodness** [comment]
Actually, I'm noticing that the time.gov site has a handy box on the right that says "your clock is off by" so as long as you can access that site from the server that's running your WordPress site, it can tell you directly whether you've got a time problem.

**Comment by torchpublishing** [comment]
Hi Kevin,

Once again thank you very much for assisting us - I really do appreciate it.

Then, open a terminal window and run date on your Mac server. It will give you the current date/time on your system. You want to compare the minutes and seconds of the time when you run that command against the minutes and seconds on the time.gov<http://time.gov> site. I don't specifically recall the threshold at which Apple's systems throw an error, but I think it's only a few seconds, so if you're noticing that the minutes aren't exact or the seconds are more than, say, 3s off, you have a time problem.

The time seems to be fine. The date result and the time.gov<http://time.gov> site seemed to align and the time.gov<http://time.gov> site determined our server was out by .03 seconds (I’m assuming that means 3/100ths of a second rather than 3 seconds). I also checked the Wordpress time zone is correctly set to Sydney and the daylight saving settings are correct.

[cid:E310B563-A655-48B2-AEFB-99BD68DEC02B]


For the secret key, you may want to try typing it into the field directly to ensure you aren't copying invisible extra characters like spaces, etc. My guess is that it's the time, but best to be sure.

I did two things here. Typed the text into BBEdit with invisibles on and pasted it in - still no luck. Then I typed it straight into the plugin settings and the same result.

FWIW, I am attaching the failed response below. I notice the time is the Apple server’s time (about 10 hours different to our time - I tried this at 9.25am) but I’m assuming the time it is looking for is the Apple News time.

I’m going to try and manually build a simple article submission to see if I can get anything to work. I’m not well versed in REST APIs or JSON but I’m willing to give it a go.

Many thanks again. If you have any further suggestions I’m all ears.


API Response:
Array
(
   [headers] => Requests_Utility_CaseInsensitiveDictionary Object
       (
           [data:protected] => Array
               (
                   [server] => AppleHttpServer/e81851ddfbfa
                   [date] => Thu, 18 Jun 2020 23:25:53 GMT
                   [content-type] => application/json;charset=utf-8
                   [content-length] => 39
                   [request-id] => 0d5c1280-b1bb-11ea-84bb-63ecf54a9f32
                   [www-authenticate] => HHMAC
                   [x-b3-traceid] => 873ef6b0f7ea80d4
                   [strict-transport-security] => max-age=31536000
               )

       )

   [body] => {"errors":[{"code":"WRONG_SIGNATURE"}]}
   [response] => Array
       (
           [code] => 401
           [message] => Unauthorized
       )

   [cookies] => Array
       (
       )

   [filename] =>
   [http_response] => WP_HTTP_Requests_Response Object
       (
           [response:protected] => Requests_Response Object
               (
                   [body] => {"errors":[{"code":"WRONG_SIGNATURE"}]}
                   [raw] => HTTP/1.1 401 Unauthorized
Server: AppleHttpServer/e81851ddfbfa
Date: Thu, 18 Jun 2020 23:25:53 GMT
Content-Type: application/json;charset=utf-8
Content-Length: 39
Connection: close
Request-Id: 0d5c1280-b1bb-11ea-84bb-63ecf54a9f32
WWW-Authenticate: HHMAC
X-B3-TraceId: 873ef6b0f7ea80d4
Strict-Transport-Security: max-age=31536000

{"errors":[{"code":"WRONG_SIGNATURE"}]}
                   [headers] => Requests_Response_Headers Object
                       (
                           [data:protected] => Array
                               (
                                   [server] => Array
                                       (
                                           [0] => AppleHttpServer/e81851ddfbfa
                                       )

                                   [date] => Array
                                       (
                                           [0] => Thu, 18 Jun 2020 23:25:53 GMT
                                       )

                                   [content-type] => Array
                                       (
                                           [0] => application/json;charset=utf-8
                                       )

                                   [content-length] => Array
                                       (
                                           [0] => 39
                                       )

                                   [request-id] => Array
                                       (
                                           [0] => 0d5c1280-b1bb-11ea-84bb-63ecf54a9f32
                                       )

                                   [www-authenticate] => Array
                                       (
                                           [0] => HHMAC
                                       )

                                   [x-b3-traceid] => Array
                                       (
                                           [0] => 873ef6b0f7ea80d4
                                       )

                                   [strict-transport-security] => Array
                                       (
                                           [0] => max-age=31536000
                                       )

                               )

                       )

                   [status_code] => 401
                   [protocol_version] => 1.1
                   [success] =>
                   [redirects] => 0
                   [url] => https://news-api.apple.com/channels/2a90c31c-aafc-4b80-96b6-6c8923d45e3d/articles
                   [history] => Array
                       (
                       )

                   [cookies] => Requests_Cookie_Jar Object
                       (
                           [cookies:protected] => Array
                               (
                               )

                       )

               )

           [filename:protected] =>
           [data] =>
           [headers] =>
           [status] =>
       )

)


Request Meta:

Array
(
   [data] => Array
       (
           [isPaid] =>
           [isPreview] =>
           [isHidden] =>
           [isSponsored] =>
       )

)


Image Settings:
Use Remote images enabled

JSON:
{"version":"1.7","identifier":"post-23168","language":"en-AU","title":"\u2018Pop up\u2019 Drive-in could cruise in","documentStyle":{"backgroundColor":"#fafafa"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"https:\/\/www.localnewsplus.com.au<http://www.localnewsplus.com.au>\/wp-content\/uploads\/2020\/06\/drive_in_T25_02.jpg"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnSpan":7,"columnStart":0,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#fafafa"},"components":[{"role":"title","text":"\u2018Pop up\u2019 Drive-in could cruise in","format":"html","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by Editor | Jun 16, 2020 | 4:51 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"intro","text":"JASON Bullock\u2019s HR Holden, with passengers Tina and Alyssa Bullock, would have been one of many vintage cars enjoying the heyday of Drive-In Cinemas which could be set to enjoy a return and possibly at Bankstown Paceway if its operations manager Steve Thurlow and Councillor Steve Tunkevski have anything to do with it.\n","textStyle":"default-intro"},{"role":"body","text":"<p>THE good old days of piling the family in the car and going to the Drive-In to watch a movie, might soon be back after Councillor Steve Tuntevski asked the council to investigate establishing a \u2018pop up\u2019 cinema, with Bankstown Paceway a likely site.<br \/>\n\u201cMany residents fondly remember going to the former Bass Hill Drive-In which operated  for half a century, and I\u2019d love to see the Drive-In Cinema undergo a renaissance in our city,\u201d Cr Tuntevski said. <br \/>\n\u201cIn these unprecedented times, it would allow families and couples to have a Covid-19 safe fun night out; they can grab a bite to eat from an array of food trucks and watch a double blockbuster movie.<br \/>\n\u201cIn their heyday, drive-in cinema\u2019s provided Friday and Saturday night entertainment for a diversity of social groups, from families and couples to carloads of teenagers.\u201d<br \/>\nBankstown Paceway Operations Manager Steve Thurlow is all for the plan.<br \/>\n\u201cOne of our board members, Terry Brooks, is helping Fairfield Council set up their \u2018pop up\u2019 cinema at the showground and we can definitely see the merit of doing it here too,\u201d Mr Thurlow said.<br \/>\n\u201cWe could operate it in the middle of the track on the grass which is not being used at the moment as there are no race meets or markets.<br \/>\n\u201cIt would be a win win situation for us and I\u2019m sure would appeal to residents of all faiths plus there are a lot of families that live around here.<br \/>\n\u201cHaving a drive-in would be a nice outlet for the community; there would be a lot of interest as it\u2019s something different. and would be an affordable outing for the whole family.\u201d<\/p>","format":"html","textStyle":"dropcapBodyStyle","layout":"body-layout-last"}]}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"AvenirNext-Bold","textColor":"#4f4f4f","numberOfRaisedLines":0}},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"tracking":0,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":13,"lineHeight":24,"tracking":0,"textColor":"#7c7c7c"},"default-intro":{"fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#4f4f4f"}},"textStyles":{"default-tag-code":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"},"default-tag-pre":{"textAlignment":"left","fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f","paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-tag-samp":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"}},"componentLayouts":{"body-layout":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":30}},"headerPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7},"headerBelowTextPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"excerpt":"JASON Bullock\u2019s HR Holden, with passengers Tina and Alyssa Bullock, would have been one of many vintage cars enjoying the heyday of Drive-In Cinemas which could be set to enjoy a return and possibly at Bankstown Paceway if its operations manager Steve Thurlow and Councillor Steve Tunkevski have anything to do with it.","thumbnailURL":"https:\/\/www.localnewsplus.com.au<http://www.localnewsplus.com.au>\/wp-content\/uploads\/2020\/06\/drive_in_T25_02.jpg","dateCreated":"2020-06-16T06:51:49+00:00","dateModified":"2020-06-16T06:51:49+00:00","datePublished":"2020-06-16T06:51:49+00:00","canonicalURL":"https:\/\/www.localnewsplus.com.au<http://www.localnewsplus.com.au>\/pop-up-drive-in-could-cruise-in\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"2.0.6"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}


MIME request:
Authorization: HHMAC; key=8958d4cd-8d53-44fe-941b-8b583906072d; signature=QcdH0lxuogG7qRY6atmvJ96wb7m5UhHajAQA944WKJA=; date=2020-06-18T23:25:52+00:00
Content-Length: 6064
Content-Type: multipart/form-data; boundary=a7da1437db7a7e6659db66d339bdc1fc

--a7da1437db7a7e6659db66d339bdc1fc
Content-Type: application/json
Content-Disposition: form-data; name=metadata

{"data":{"isPaid":false,"isPreview":false,"isHidden":false,"isSponsored":false}}
--a7da1437db7a7e6659db66d339bdc1fc
Content-Type: application/json
Content-Disposition: form-data; name=my_article; filename=article.json; size=5674

{"version":"1.7","identifier":"post-23168","language":"en-AU","title":"\u2018Pop up\u2019 Drive-in could cruise in","documentStyle":{"backgroundColor":"#fafafa"},"layout":{"columns":7,"width":1024,"margin":100,"gutter":20},"components":[{"role":"header","layout":"headerPhotoLayout","components":[{"role":"photo","layout":"headerPhotoLayout","URL":"https:\/\/www.localnewsplus.com.au<http://www.localnewsplus.com.au>\/wp-content\/uploads\/2020\/06\/drive_in_T25_02.jpg"}],"behavior":{"type":"parallax","factor":0.8}},{"role":"container","layout":{"columnSpan":7,"columnStart":0,"ignoreDocumentMargin":true},"style":{"backgroundColor":"#fafafa"},"components":[{"role":"title","text":"\u2018Pop up\u2019 Drive-in could cruise in","format":"html","textStyle":"default-title","layout":"title-layout"},{"role":"byline","text":"by Editor | Jun 16, 2020 | 4:51 PM","textStyle":"default-byline","layout":"byline-layout"},{"role":"intro","text":"JASON Bullock\u2019s HR Holden, with passengers Tina and Alyssa Bullock, would have been one of many vintage cars enjoying the heyday of Drive-In Cinemas which could be set to enjoy a return and possibly at Bankstown Paceway if its operations manager Steve Thurlow and Councillor Steve Tunkevski have anything to do with it.\n","textStyle":"default-intro"},{"role":"body","text":"<p>THE good old days of piling the family in the car and going to the Drive-In to watch a movie, might soon be back after Councillor Steve Tuntevski asked the council to investigate establishing a \u2018pop up\u2019 cinema, with Bankstown Paceway a likely site.<br \/>\n\u201cMany residents fondly remember going to the former Bass Hill Drive-In which operated  for half a century, and I\u2019d love to see the Drive-In Cinema undergo a renaissance in our city,\u201d Cr Tuntevski said. <br \/>\n\u201cIn these unprecedented times, it would allow families and couples to have a Covid-19 safe fun night out; they can grab a bite to eat from an array of food trucks and watch a double blockbuster movie.<br \/>\n\u201cIn their heyday, drive-in cinema\u2019s provided Friday and Saturday night entertainment for a diversity of social groups, from families and couples to carloads of teenagers.\u201d<br \/>\nBankstown Paceway Operations Manager Steve Thurlow is all for the plan.<br \/>\n\u201cOne of our board members, Terry Brooks, is helping Fairfield Council set up their \u2018pop up\u2019 cinema at the showground and we can definitely see the merit of doing it here too,\u201d Mr Thurlow said.<br \/>\n\u201cWe could operate it in the middle of the track on the grass which is not being used at the moment as there are no race meets or markets.<br \/>\n\u201cIt would be a win win situation for us and I\u2019m sure would appeal to residents of all faiths plus there are a lot of families that live around here.<br \/>\n\u201cHaving a drive-in would be a nice outlet for the community; there would be a lot of interest as it\u2019s something different. and would be an affordable outing for the whole family.\u201d<\/p>","format":"html","textStyle":"dropcapBodyStyle","layout":"body-layout-last"}]}],"componentTextStyles":{"dropcapBodyStyle":{"textAlignment":"left","fontName":"AvenirNext-Regular","fontSize":18,"tracking":0,"lineHeight":24,"textColor":"#4f4f4f","linkStyle":{"textColor":"#428bca"},"paragraphSpacingBefore":18,"paragraphSpacingAfter":18,"dropCapStyle":{"numberOfLines":4,"numberOfCharacters":1,"padding":5,"fontName":"AvenirNext-Bold","textColor":"#4f4f4f","numberOfRaisedLines":0}},"default-title":{"fontName":"AvenirNext-Bold","fontSize":48,"lineHeight":52,"tracking":0,"textColor":"#333333","textAlignment":"left"},"default-byline":{"textAlignment":"left","fontName":"AvenirNext-Medium","fontSize":13,"lineHeight":24,"tracking":0,"textColor":"#7c7c7c"},"default-intro":{"fontName":"AvenirNext-Regular","fontSize":18,"lineHeight":24,"textColor":"#4f4f4f"}},"textStyles":{"default-tag-code":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"},"default-tag-pre":{"textAlignment":"left","fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f","paragraphSpacingBefore":18,"paragraphSpacingAfter":18},"default-tag-samp":{"fontName":"Menlo-Regular","fontSize":16,"tracking":0,"lineHeight":20,"textColor":"#4f4f4f"}},"componentLayouts":{"body-layout":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":12}},"body-layout-last":{"columnStart":0,"columnSpan":6,"margin":{"top":12,"bottom":30}},"headerPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7},"headerBelowTextPhotoLayout":{"ignoreDocumentMargin":true,"columnStart":0,"columnSpan":7,"margin":{"top":30,"bottom":0}},"title-layout":{"margin":{"top":30,"bottom":0}},"byline-layout":{"margin":{"top":10,"bottom":10},"columnStart":0,"columnSpan":7}},"metadata":{"excerpt":"JASON Bullock\u2019s HR Holden, with passengers Tina and Alyssa Bullock, would have been one of many vintage cars enjoying the heyday of Drive-In Cinemas which could be set to enjoy a return and possibly at Bankstown Paceway if its operations manager Steve Thurlow and Councillor Steve Tunkevski have anything to do with it.","thumbnailURL":"https:\/\/www.localnewsplus.com.au<http://www.localnewsplus.com.au>\/wp-content\/uploads\/2020\/06\/drive_in_T25_02.jpg","dateCreated":"2020-06-16T06:51:49+00:00","dateModified":"2020-06-16T06:51:49+00:00","datePublished":"2020-06-16T06:51:49+00:00","canonicalURL":"https:\/\/www.localnewsplus.com.au<http://www.localnewsplus.com.au>\/pop-up-drive-in-could-cruise-in\/","generatorIdentifier":"publish-to-apple-news","generatorName":"Publish to Apple News","generatorVersion":"2.0.6"},"advertisingSettings":{"frequency":1,"layout":{"margin":{"top":15,"bottom":15}}}}
--a7da1437db7a7e6659db66d339bdc1fc—







Kim Kohen | Torch Publishing Company Pty Ltd
Prepress and Systems Manager

47 Allingham St, Condell Park, NSW 2200 | Ph: (612) 9795 0000 | Mob: 0411 796 560 | LocalNewsPlus <http://www.localnewsplus.com.au>
Publishers of Canterbury Bankstown Torch | Auburn Review | Inner West Times

Confidentiality Information
This email and any attachments are confidential and may be subject to copyright, legal or some other professional privilege. They are intended solely for the attention and use of the intended recipient(s). They may only be copied, distributed or disclosed with the consent of the copyright owner. If you have received this email by mistake or by breach of the confidentiality clause, please notify the sender immediately by return email and delete or destroy all copies of the email. Any confidentiality, privilege or copyright is not waived or lost because this email has been sent to you by mistake. We will aggressively defend any breaches of copyright resulting from this email.

**Comment by torchpublishing** [comment]
This is so frustrating - just totally stuck with nowhere to go. I'm now trying to navigate Apple's less than helpful API information. I have a perfectly formed article.json but can't for the life of me work out how to send it to Apple via the API.

**Comment by kevinfodness** [comment]
I'm sorry that I can't be more help here - if your channel information is correct and the time on your server is correct, then there is no reason that I know if why this would be failing. I would suggest opening a ticket with Apple support so that they can help you diagnose the problem from their end, since this error is ultimately coming from their API.

**Comment by torchpublishing** [comment]
I sent an email to Apple News Format support. It took several days to get a reply but their recommendation was to simply re-generate the keys. I did this and lo and behold it's now working.

Thank you Kevin for you attempts to help - it's been an infuriating couple of weeks but we seem to be on the way now. We have our three stories in the review process and hopefully it wont take too long.

**Comment by kevinfodness** [comment]
Glad to hear it! I'm sorry that the issue was so difficult to resolve.
