### ISSUE TITLE
SOLVED Cannot See Apple News Pinned Widget in Editor - pluginSidebar.js

### ISSUE THREAD

**Issue by robert-huttinger** [alleyinteractive/apple-news#746]
When using the editor for a post, the button to set the options re Apple News Publishing isn't there. We have Yoast enabled via code (using Irving), and that button appears. With Ypast we can pin/unpin, as well as activate/de-activate, but the Apple News button isnt there. 

re-installed and updated the plugin, no love.

**The problem we are trying to solve:**
There are some posts we do not want published to Apple News.

Since this feature is not working is there a hook we can use to check if a category or tag exists, and if so, set the isHidden flag or similar to preclude publishing?

PS: This would be a great additional feature. In the settings have text fields for categories, and tags. If a post contains any||all then don't publish. Or conversely, only posts with specific cats or tags publish.

<img width="272" alt="Screen Shot 2020-07-08 at 2 18 14 PM" src="https://user-images.githubusercontent.com/56265388/87204074-f2761600-c2d1-11ea-8475-aac4ab7474e5.png">

We do have the widget 'on'
<img width="822" alt="Screen Shot 2020-07-08 at 9 22 18 AM" src="https://user-images.githubusercontent.com/56265388/87204480-ea6aa600-c2d2-11ea-9c19-9176aee4983f.png">

**Comment by kevinfodness** [comment]
Can you open your developer console and see if there is a JavaScript error that could be preventing the PluginSidebar component for Apple News from displaying? In Chrome, you would do this by right clicking anywhere on the page and selecting Inspect, then going to the Console tab and looking for anything in red, which should have error text. Since you aren't seeing the icon and it's not appearing in the dropdown, it feels to me like you're not getting the JavaScript for the PluginSidebar at all, or it's resulting in an error. If there are no errors, you can also use the Network tab in the developer tools to see if the PluginSidebar code is even being fetched - just reload the admin view and look for something called `pluginSidebar.js`. If you don't see it, then there's an issue that's preventing it from being called.

How have you installed the plugin? Via normal means, or by submodule inclusion? If you're using a submodule, you need to make sure you check out one of the `-built` tags, like `v2.0.8-built`, otherwise the built JavaScript assets for the PluginSidebar aren't included.

**Comment by robert-huttinger** [comment]
Normal installation. Looking at the generated code via inspector there are no elements at all. 

Its embarrassing I didnt look at this sooner, but there is this error:
GET https://my-super-site.com/wp-content/plugins/publish-to-apple-news/build/pluginSidebar.js?ver=2.0.8 net::ERR_ABORTED 404

It, and several other things are being blocked...

That file isnt there, and doesnt exist. Ill see if I can locate the asset and install it...

**Comment by kevinfodness** [comment]
If you install the latest version of the plugin from WordPress.org it should be there. I just downloaded the latest version locally and extracted it, and the asset is indeed in the build folder. If you installed the plugin from source on GitHub, you need to ensure you've got the latest `-build` tag checked out. We don't commit the built assets to the head branch on the repo, and when we tag releases, there is a "source" version and a "built" version, and you should always use the "built" version if you are using GitHub as your source instead of WordPress.com. The latest built version tag is `v2.0.8-built`.

**Comment by robert-huttinger** [comment]
I see what the issue is. `build` is not allowed to be added to the repo. Based on a colleagues advice we looked in the .gitignore file and sure enough `build` was there. Apparently this was missed by the original contractor as well its such a minor thing. This is alsow why the build dir wasnt present in the initial install as well, even though it existed in version 2.0.3.

Raj suggested using `git add --force build` we were able to get it up, after the deploy script ran, we are in business!!

The Apple News icon is there now!

Perhaps renaming the dir from 'build' to something else?

**Comment by kevinfodness** [comment]
This is in a gitignore file that you have in a parent directory, not in the Apple News plugin directory, correct?

`build` is a pretty standard name and is representative of what the directory contains. You could allow that directory in your gitignore by doing something like `!plugins/publish-to-apple-news/build`.

**Comment by robert-huttinger** [comment]
as far as I know we have a vanilla gitignore file in the parent/root. afaik nobody changed the gitignore file. For sure we can add that path as an exception, but I wonder how many others are seeing this issue? 

Dont know, but Im glad we found the issue and hope others can benefit!

**Comment by kevinfodness** [comment]
A "vanilla" gitignore file would be empty - I'm sure it was generated with a predefined config somewhere, but ignoring a `build` folder at the root of a repo that contains third party code in the `plugins` folder is a recipe for this type of disaster. In any case, we have this issue with documented steps to fix, which others can find if they're having similar issues. I'm going to leave the `build` folder name as-is in the plugin unless this ends up becoming a widespread issue.

Thanks for the report, and I'm glad you got it working!
