### ISSUE TITLE
Page Builder Shortcode Appears In Published Articles On Apple News

### ISSUE THREAD

**Issue by RyanLAFB** [alleyinteractive/apple-news#834]
On my WordPress site, I use WPBakery Page Builder in all of my posts. When my articles post to Apple News, the shortcode that is used on the backend within the page builder is displayed in the published article on Apple News.

<img width="1164" alt="Screen Shot 2021-02-24 at 10 53 43 PM" src="https://user-images.githubusercontent.com/66980186/109114980-3c8df980-76f3-11eb-810f-28e80350a26c.png">

**Comment by kevinfodness** [comment]
Typically, this happens when a plugin only registers its shortcodes in a front-end context (e.g., it does an `is_admin()` check and bails out, and doesn't register the shortcode). In order for Publish to Apple News to work properly, all shortcodes must be registered in the admin context as well as the front-end, because the plugin generates the JSON for the article in an admin context.

We typically don't add support for third party plugins to the Publish to Apple News plugin itself (there are simply too many of them). However, you could likely solve this yourself by determining what code in the plugin _should_ be running to register that shortcode, and adding some logic to your theme to register it in an admin context also.
