### ISSUE TITLE
Play button gone on articles with video

### ISSUE THREAD

**Issue by itskentk** [alleyinteractive/apple-news#850]
Before a recent update, all of our articles that had a video component would have a play button on the thumbnail in the feeds of Apple News. This has since disappeared. Per a conversation with Apple News, we replaced (Line 81) of the (class-metadata.php) file as follows"
if ( preg_match( ’/src=“([^\?“]+\.mp4[^“]*)“|src=“([^\?“]+\.m3u8[^“]*)“/’, $matches[2][ $i ], $src ) ) {
In an attempt to get the play button back, but have had no luck.

**Comment by kevinfodness** [comment]
Hi @itskentk - we will be addressing this in an upcoming update. We're working on adding support for `m3u8` files, and I have a bugfix in an in-progress branch right now for matching video elements where the `src` is specified in the `<video>` tag itself, rather than in a `<source>` tag within the `<video>` tag.

To ensure we are fixing the issue that you're describing, can you please include either a link to the web view of the article that has the issue, or the HTML for the video element that isn't being parsed properly?

Thanks.

**Comment by kevinfodness** [comment]
@itskentk - I just released version 2.1.3 of the plugin, which contains a fix for this issue, as I understand it. Can you give it a try and let me know if it fixes the issue for you?
