### ISSUE TITLE
Showing the 'Custom fields' doesn't allow to save the Options

### ISSUE THREAD

**Issue by elaverdiere-mishmash** [alleyinteractive/apple-news#851]
While editing a post, if you show the 'custom fields' (Preferences -> Panel -> Custom fields), the Apple News options (like Paid, or Sponsored) won't be saved if changes are made.

**Comment by kevinfodness** [comment]
Thanks for the issue report - I'll look into it.

**Comment by kevinfodness** [comment]
OK, I think I see what's going on here. Basically, the values get set via the REST API request from the plugin and then get _unset_ by the follow-up post from the custom fields area. I'm marking this as an enhancement, since it's likely that the number of users who have the custom fields view enabled in Gutenberg is fairly low. If possible, we should prevent Apple News fields from appearing under Custom Fields at all if Gutenberg is active.

**Comment by kevinfodness** [comment]
I'm closing this - this is the only report I've had of this issue and doesn't merit building support into the plugin for this narrow use case.
