### ISSUE TITLE
API: INVALID_DOCUMENT - The value for the property "URL" at line 1 and column 817 is not valid

### ISSUE THREAD

**Issue by cm3solutions** [alleyinteractive/apple-news#852]
Getting the following error when I publish an article

API: INVALID_DOCUMENT - The value for the property "URL" at line 1 and column 817 is not valid: /wp-content/uploads/2021/06/Rock.jpg (keyPath components->2->components->0->URL)

All the plugins I use I need, so disabling one will not help me. I would let to edit the code so I can add the site URL to it. Can you tell me where in the code the json gets built?

headerPhotoLayout & thumbnailURL seem to be where the issue is. I just need to add https://xflnewshub.com to the front of the token somehow.

[article-15279.txt](https://github.com/alleyinteractive/apple-news/files/6656397/article-15279.txt)

**Comment by kevinfodness** [comment]
Hi @cm3solutions — the issue there appears to be that the image is a relative URL rather than an absolute one, so Apple doesn't know what domain to contact to fetch the image file. There is code in the plugin that should automatically be prepending the site's root URL to root-relative URLs, but it appears that there is something interfering with that functionality here.

There are a number of filters you can use to modify what the plugin generates, which are documented in [our wiki](https://github.com/alleyinteractive/apple-news/wiki). The final JSON can be filtered using the [apple_news_generate_json filter](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_generate_json), where you should be able to iterate through the array containing the data to be saved to JSON and perform replacements on root-relative URLs to include your domain name.

If you are also having issues with the metadata being sent to Apple, and I'm going to guess that you are, then you will need to filter [apple_news_metadata](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_metadata) as well.

**Comment by kevinfodness** [comment]
I found the issue—we are doing root-relative URL handling in other parts of the codebase, but not in the specific case of a filter that is applied to image URLs that fires for featured images where featured images are used as the Cover component in an Apple News article. I added a fix to a PR that I was authoring for URL handling generally, since I was already in the neighborhood in the codebase.
