### ISSUE TITLE
Getting WRONG_SIGNATURE error

### ISSUE THREAD

**Issue by mossifer** [alleyinteractive/apple-news#853]
My client is getting WRONG_SIGNATURE error when posting an article. Does this error have to do with credentials?  I can send you the debug notification if that would help.

**Comment by kevinfodness** [comment]
Yes, the debug notification would be helpful. Typically, the `WRONG_SIGNATURE` error is due to one of two things: either your channel credentials aren't entered correctly (channel ID, key, and secret) or the time on the web server is different than what is on Apple's systems. The request that your site makes to Apple's API is signed, and part of the signature includes the current timestamp, and if that timestamp is off by more than a minute or so, Apple's API will reject the request with a `WRONG_SIGNATURE` error. If you have access to the server that's running the site where you are trying to use the plugin, you can use a tool like `ntp` to re-synchronize the date and time on the server with an atomic clock. If you don't have access to the server, you should ask your hosting company to do this for you.
