### ISSUE TITLE
Is there any developer of the Publish to Apple News plugin available for hire?

### ISSUE THREAD

**Issue by johnllyman** [alleyinteractive/apple-news#877]
Hello.  I'm still having some issues with settings for titles and on the backend with the error message NOT_FOUND (keyPath articleId) so is there anyone available for probably 30 mins max to just go into my backend and fix whatever issues I might be having with the plugin?

**Comment by kevinfodness** [comment]
Hi @johnllyman - if you're getting `NOT_FOUND` that likely means that the article was deleted from iCloud News Publisher directly rather than being deleted via the plugin. The plugin maintains an association between the posts on your WordPress site and the article IDs on News Publisher, so if you delete it from the News Publisher side, your WordPress site isn't aware of that and is trying to access the article by its cached ID. For specific articles where you are experiencing this issue, you should be able to delete any Apple News postmeta attached to that post using a direct database command. For example: 

```sql
DELETE FROM wp_postmeta WHERE post_id = ? AND meta_key LIKE 'apple_news_%';
```

You would just need to replace the `?` in the above command with the ID of the post you wanted to reset.

**Comment by johnllyman** [comment]
Hi Kevin. I apologize again for all the posts. A developer was able to sort it out.  I do appreciate your help.

**Comment by kevinfodness** [comment]
Glad to hear it!

**Comment by johnllyman** [comment]
Hi Kevin.  Should be one of my final questions that I have but it's about missing a step when publishing. My Apple News page doesn't display all the articles on the main tab and one or two I have components moved around or removed are still present on some articles.  Do I also need to go into the list of articles and hit publish for the ones that it shows have been published? I hope that makes sense.  The developer reverted the plugin to an earlier version so do I need to update the plugin?

**Comment by kevinfodness** [comment]
> My Apple News page doesn't display all the articles on the main tab and one or two I have components moved around or removed are still present on some articles. Do I also need to go into the list of articles and hit publish for the ones that it shows have been published? I hope that makes sense. 

I'm assuming you're talking about the channel view in the News app here. Published articles that are not hidden or previews should appear in the listing on your channel. However, if they are published to different sections, you may need to change the active section view in order to see them - only articles published to the Main section will appear on the main view of your channel. If you have confirmed that the articles are published, are not marked as a preview or hidden, and should be visible on the main section, but still are not visible, then you should follow up with Apple's support to determine why you can't see them in your channel. The plugin will give you a link to the article on Apple News (available in the last section of the Apple News sidebar) which you can use to verify that it does, in fact, exist on the Apple News side.

> The developer reverted the plugin to an earlier version so do I need to update the plugin?

Yes, I would recommend updating to the latest version.

**Comment by Kevinlearynet** [comment]
If anyone finds this conversation off Google, I'm a developer that supports this Apple News plugin for sites like [tripadvisor.com](https://www.tripadvisor.com/blog/) and [neo.life](https://neo.life). If you need any support ongoing I'd be happy to help: [kevinleary.net](https://www.kevinleary.net/)
