### ISSUE TITLE
Allow publishing of posts to Apple News when WP CLI is being used

### ISSUE THREAD

**Issue by stuartshields** [alleyinteractive/apple-news#883]
Currently the plugin only allows for posts to be published in the following ways:
1. When a post is created / updated / deleted from the WP Admin
2. When a post is created via a cronjob

see: https://github.com/alleyinteractive/apple-news/blob/develop/admin/class-admin-apple-post-sync.php#L73

This causes a few issues, because when you use WP CLI to run a script to create / update / delete posts in our case a 3rd party feed via crontab the publishing to Apple News doesn't happen.

While our solution internally is to run the WP Cron command: `wp cron event run syn_pull_content` it is not documented at all that this is the way to publish posts created and means that if we do need to run WP CLI commands for missed articles etc. they wouldn't be published to Apple News.

Solution would be:
1. Allow for the ability to publish posts to Apple News when a post in WP is created via WP CLI
2. Update documentation in the meantime to reflect that it isn't possible to publish posts when created via WP CLI until the above is done.

**Comment by kevinfodness** [comment]
This behavior is on purpose, because it's possible to modify a significant number of posts via CLI in a short period of time, which would involve sending a lot of posts to Apple at once. Apple restricts the number of articles that can be published within a 24-hour period (https://developer.apple.com/documentation/apple_news/create_an_article, see HTTP status 429) and throttles updates (https://developer.apple.com/documentation/apple_news/update_an_article, see example responses). Therefore, the plugin doesn't currently permit bulk programmatic updates in this way.

However, the plugin does support async publishing via cron, so you may be able to work something out with async publishing enabled and adding cron jobs (perhaps programmatically).

**Comment by stuartshields** [comment]
@kevinfodness Understandable, however I do think this needs to be added to the wiki on the plugin (unless it already has been and I'm looking at the wrong spot), as I don't see it on this page? https://github.com/alleyinteractive/apple-news/wiki/usage#troubleshooting

**Comment by kevinfodness** [comment]
You're right that we could call that out in the wiki. I'll make that change.

**Comment by kevinfodness** [comment]
Added: https://github.com/alleyinteractive/apple-news/wiki/usage#auto-sync-and-wp-cliwordpress-cron
