### ISSUE TITLE
'apple_news_generate_json' filter doesn't return image captions

### ISSUE THREAD

**Issue by fraserboag** [alleyinteractive/apple-news#912]
If you var_dump($json) using this filter, the data returned is an array of your post's component blocks.

Any image blocks in this array show the "role", "URL" and "layout", but not the image's caption.

I use this filter to build a custom template for our articles in Apple News, so access to the caption here would be useful.

Apologies in advance if this isn't an issue and this data should be picked up in a different filter or something, but I probed around and couldn't find where.

**Comment by fraserboag** [comment]
If you var_dump($json) using this filter the data returned is an array of your post's component blocks.

Any image blocks in this array show the "role", "URL" and "layout", but not the image's caption.

I use this filter to build a custom template for our articles in Apple News, so access to the caption here would be useful.

**Comment by kevinfodness** [comment]
This would actually be an issue with the Image component, rather than the filter. The Image component is responsible for breaking down images and adding captions to them if it is able to identify a caption within the markup, using markup signatures that it's familiar with (broadly, the `[caption]` shortcode and the image Gutenberg block). That component's source is here: https://github.com/alleyinteractive/apple-news/blob/develop/includes/apple-exporter/components/class-image.php

How are you building your images with captions? If you're using something other than the WordPress standard shortcodes or Gutenberg blocks, it's entirely likely that the Image component isn't recognizing the caption that is associated with your image and it isn't parsing it out. You may need to filter the Image component itself in order to add some parsing logic that is unique to your circumstance. For example, you could use https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_%7B%24component_name%7D_json in combination with some custom code that extracts a caption from post_content for a given post by matching it to the URL returned by the image component and appending it there. You can see the structure that the Image component is expecting in the link above (the caption element).
