### ISSUE TITLE
Apple News API CLI/configuration: programmer level knowledge needed for a plugin (?)

### ISSUE THREAD

**Issue by yeoldemother** [alleyinteractive/apple-news#916]
Hello,

I am not a programmer, but a publisher. This set-up has stumped me, and I wonder if someone would be able to help?

Following [this installation guide](https://github.com/alleyinteractive/apple-news/wiki/Configuration), I have the iCloud News Publisher set up, and the Publish To Apple News plugin too; all straightforward stuff. I have all the keys and ids. I even have a .papi file. But then I get to the bit where this happens:

_Verify your connection to the Apple News API using the CLI and the .papi file you just created. To do this, run the following command in a terminal:

papi-client channel get_

I am not a programmer. Is this instruction to run this code on Terminal supposed to be on my local iMac? Or the server which I don't access with Terminal because it's a server? I added that line of code and Terminal prompted me with "Password?" What's the password? Why am I using Terminal?

_If you cannot connect via the Apple News API CLI, you cannot connect via the Publish to Apple News plugin, so it is important to get this step working before proceeding to configuring the plugin. If you have any difficulty with making a connection via the CLI, you will need to follow up with Apple support._

Apple Support are not going to tell me how to run Terminal commands, or where. 

I've been told to download Xcode. What am I meant to do with that?

Why is this so complicated, please? And can anyone make it less so, so our articles can carry over to Apple News? 

Yours in hope, 

Michael

**Comment by kevinfodness** [comment]
Working with Apple News is very technical, even with the addition of this plugin. The plugin is meant to make certain things easier (customizing colors, fonts, etc) but does not preclude developer involvement in getting the integration working properly. For instance, on all but the most basic WordPress sites, there will be customizations to the site that require writing code to filter the output of the plugin to ensure that everything is sent to Apple correctly, since the plugin isn't able to be automatically compatible with all of the possible third party plugins and customizations that are available for WordPress.

The instructions for configuring the `.papi` file and verifying connection to the Apple News API come directly from Apple's documentation. The plugin will not work if the API connection cannot be made, or if the credentials are not correct. You can, of course, upload the `.papi` file to the Apple News settings screen on your WordPress site without verifying the connection first, but if the connection cannot be made, you will just get an error message about not being able to connect to the API, which is likely less helpful than what the Apple News API CLI will give you.
