### ISSUE TITLE
Hard to detect image parsing issue

### ISSUE THREAD

**Issue by kimmilodetroit** [alleyinteractive/apple-news#936]
https://pastebin.com/LiQeVpdx

**Comment by kevinfodness** [comment]
Please follow the instructions in [Getting Help](https://github.com/alleyinteractive/apple-news/wiki/Usage#getting-help) so that we have enough information to be able to help you. All you provided is a pastebin link, so I don't know what the error was from Apple (failed to parse image at what URL? what position in the JSON? etc).
