### ISSUE TITLE
error with the Apple News API: INVALID_DOCUMENT - Unable to read uri 

### ISSUE THREAD

**Issue by jiaoqiqi** [alleyinteractive/apple-news#942]
Hi team, 

We are using this plugin recently but there has errors when publish to Apple News like 
```
There has been an error with the Apple News API: INVALID_DOCUMENT - Unable to read uri [https://dam-assets.au.reastatic.net/images/f_auto,q_auto/v1657171701/news-lifestyle-content-assets/wp-content/production/capi_eed5171ac633beb37d40327f252a742e_7ff5d8b54bc98d2ba69fbc3039024eab/capi_eed5171ac633beb37d40327f252a742e_7ff5d8b54bc98d2ba69fbc3039024eab.jpeg?_i=AA]
```

Actually the image url is accessible when open it from browser, also we published that to Apple News before. you can see it here: https://apple.news/AYEXIk94DRbKdv5dO4PuDsg

But when I update the article then will have the above errors. Could you help to have a look about this one?

**Comment by jiaoqiqi** [comment]
I also download the json file for the article, and the image url is also same with when in Wordpress edit mode.

**Comment by kevinfodness** [comment]
Has something changed with permissions to that server? Apple needs to be able to pull the image from that URL onto its servers when the article is published, so if `dam-assets.au.reastatic.net` is blocking access from Apple's servers, that could be what is causing the issue.

**Comment by jiaoqiqi** [comment]
Hi kevinfodness, thanks for your reply, I don't think the permission has changed, the whole process is like I uploaded one image to an article, then could publish to Apple News, and then next time when I update my article, there has errors. But the image url doesn't change. Also in the published News, the image url domain is also `dam-assets.au.reastatic.net`

And I will check whether dam-assets.au.reastatic.net` blocked access from Apple's servers.

**Comment by kevinfodness** [comment]
The error message is coming from Apple's servers and is saying that it can't access the image at that URL, which is _usually_ a result of a server blocking access. I'd recommend following up with Apple next, because they might be able to give you more information on why they weren't able to download that image.

**Comment by jiaoqiqi** [comment]
Thanks for your suggestion, I will check with them.

**Comment by jiaoqiqi** [comment]
Hi kevinfodness, there has something confusing,  we have one article with thumbnail and the link is `https://dam-assets.au.reastatic.net/images/v1657678066/news-lifestyle-content-assets/wp-content/production/GettyImages-543528948-2_7647369f2ab_764736ff808/GettyImages-543528948-2_7647369f2ab_764736ff808.jpg?_i=AA`

The first time when I try to publish the article to Apple News, it's successful. I think that means Apple could access  `dam-assets.au.reastatic.net`

But when I want to update the article, and publish to Apple News again, then there are issues like `INVALID_DOCUMENT - Unable to read uri` with the exactly same image url that was previously successful.

**Comment by kevinfodness** [comment]
That is certainly strange. Did Apple support give you any indication of what might be going wrong on their end?

**Comment by jiaoqiqi** [comment]
Hi kevinfodness, we have some new finding about publish to apple news, because we are using Cloudinary, the image url in Media Library File Url will be like https://dam-assets.au.reastatic.net/images/w_800,h_450/v1658361736/news-lifestyle-content-assets/wp-content/production/capi_4d79c834177c555b7e7b7d1019d52790_1503e93dece53504a3faca1185d3b10e/capi_4d79c834177c555b7e7b7d1019d52790_1503e93dece53504a3faca1185d3b10e.webp?_i=AA

And we add some logs when try to publish, such as this part
```php
// Get sections.
$this->sections = Admin_Apple_Sections::get_sections_for_post( $this->id );
error_log(print_r($this->sections, true));

// Generate the JSON for the article.
list( $json, $bundles, $errors ) = $this->generate_article();
error_log(print_r($json, true));

// Process errors.
$this->process_errors( $errors );

// Sanitize the data before using since it's filterable.
$json = $this->sanitize_json( $json );
 error_log(print_r($json, true));
```
But here in section and in json, the image url is
https://www.realestate.com.au/news/wp-content/uploads/2022/07/capi_4d79c834177c555b7e7b7d1019d52790_1503e93dece53504a3faca1185d3b10e.jpeg wich is not same with that in Media Library.

Do you have any idea about why this happens?

**Comment by kevinfodness** [comment]
My guess is that you're using a plugin or custom code in your theme to update image URLs to point at Cloudinary, and that that code is only firing for front-end requests, or may not be firing for REST requests (if you're using the new WordPress block editor, sometimes referred to as Gutenberg). Apple News exports and publish actions happen in an admin or REST context. I've seen this before with some other third party plugins and we've worked around it on our projects by manually adding the hooks that are necessary for those plugins to operate (which would normally be added on a front-end request, but not on an admin request). 

We have to do this for the Brightcove Video Connect plugin, as you can see here: https://github.com/alleyinteractive/apple-news/blob/e96696b8fc887a8b807a771d01d0b797e2115df2/admin/apple-actions/index/class-export.php#L538-L548

This is due to code in the Brightcove Video Connect plugin that prevents it from initializing on non-front-end requests here: https://github.com/10up/brightcove-video-connect/blob/1.3.0/brightcove-video-connect.php#L60

(Note that this code has been changed for more recent versions of the Brightcove Video Connect plugin.)

Apple News should still be able to get the image from the URL that it's currently using as long as those requests are not being blocked or throttled in some way. I was able to click through to the JSON URL you provided above and it loaded for me, so I suspect that something is preventing Apple from being able to download that image.

A few other potential wrinkles:

- When you download the JSON for an article from Apple News > Articles, it uses _mostly_ but _not exactly the same_ conditions to export the article. There are some differences, such as being in an admin context instead of a REST context if you're publishing from the block editor, which could affect what's included in the actual JSON that is sent to Apple. You can turn on debug mode in Apple News > Settings and provide your email address and you will get a copy of the actual JSON that was sent to Apple, which will help you diagnose the issue.
- Apple does not support .webp images, so if the Cloudinary code is indeed taking over with what is being sent to Apple, then it's possible that Apple is rejecting your article because it has an image that is in a format that it can't handle.
