### ISSUE TITLE
Custom Fonts Not Available in Theme

### ISSUE THREAD

**Issue by cherifzouein** [alleyinteractive/apple-news#943]
Hello,

Apologies if this was logged already, I haven't found a similar issue though.
We've successfully uploaded custom fonts to our News Publisher account but when creating a custom theme with the plugin I don't see them available in the dropdown. Is the expectation that we use JSON directly to declare these?

Thanks!

**Comment by kevinfodness** [comment]
You can use the [apple_news_fonts_list filter](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_fonts_list) to add your custom fonts to the selection list in the theme. Note that you will also need to install those custom fonts on your machine in order to see the preview when editing the theme.

**Comment by cherifzouein** [comment]
Thanks!
