### ISSUE TITLE
Apple News API: INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->24->text)

### ISSUE THREAD

**Issue by mayall** [alleyinteractive/apple-news#945]
This story:

https://santacruzlocal.org/2022/06/07/santa-cruz-county-district-4-supervisor-early-election-results/

Produces this API error:

There has been an error with the Apple News API: INVALID_DOCUMENT - "text" was "" should be not (null or an empty string) (keyPath components->1->components->24->text)

JSON file:

[article-11419.json.zip](https://github.com/alleyinteractive/apple-news/files/9160818/article-11419.json.zip)

Thanks!

**Comment by kevinfodness** [comment]
If you look in your JSON and follow the path the error message gives you (`components->1->components->24->text`) it leads you to this:

```json
        {
          "role": "body",
          "text": "<p>&#013;\n <\/p>",
          "format": "html",
          "textStyle": "default-body",
          "layout": "body-layout"
        },
```

which is an empty paragraph (a carriage return followed by a line break followed by a space, no actual text) which Apple rejects. Looking at what's above that, there's a prompt for an `Email address:` and looking at your article it's the box that prompts the user to sign up for updates, and the missing piece is the form field, which Apple does not support. You will need to remove the email signup form from your article before passing it to Apple News for processing. This should be done in code, likely using the [apple_news_exporter_content_pre filter](https://github.com/alleyinteractive/apple-news/wiki/Filter:-apple_news_exporter_content_pre) which will let you remove the shortcode/block/whatever you are using to inject the email signup into your article. If you like, you could replace it with a link back to the original article that a user could follow on Apple News in order to fill out the form on your site.

Good luck!

**Comment by mayall** [comment]
Thank you so much for your superb help!
