### ISSUE TITLE
Having issues with the plugin

### ISSUE THREAD

**Issue by squeakydavid** [alleyinteractive/apple-news#948]
Hi I'm having issues with the plugin, all my articles are set to pending at the moment not sure where to go

**Comment by kevinfodness** [comment]
Hi @squeakydavid —

Has Apple approved your channel yet? You can't publish articles until they do, and they will be stuck in "pending" status, as you described.

**Comment by squeakydavid** [comment]
Heya, how do you submit articles to Apple to be approved if you can't connect the CMS to it

**Comment by kevinfodness** [comment]
The articles have been submitted to Apple via the Publish to Apple News plugin in the CMS, but Apple needs to review them before they will allow them to be published. If you're going to use a plugin like this one to publish articles from the CMS, Apple actually requires you to do this so that they can ensure your plugin settings are correct.

More info here: https://developer.apple.com/documentation/apple_news/getting_started_as_an_apple_news_publisher

Specifically:

> Before you can publish content to Apple News, you must submit an application to the Apple News team, including information about your publication and samples of your content.

More information on the application process can be found here:

https://support.apple.com/guide/news-publisher/apply-to-publish-to-apple-news-apde42330c66/1.0/icloud/1.0

**Comment by squeakydavid** [comment]
Ok, thank you :)
