### ISSUE TITLE
Articles publishing to Apple News using Autosync but not storing apple_news_api_id 

### ISSUE THREAD

**Issue by richhaynie** [alleyinteractive/apple-news#981]
Periodically we have articles that are correctly showing up in AppleNews and look like they were automatically published using this plugin but none of the post meta is set (all show up as empty) .

The only way for us to fix this so we can get Apple News status is to manually set the apple_news_api_id.

I've looked through the code and at the articles but nothing stands out.  Is there any known issues with publishing some articles to Apple News where those settings don't come out.

**Comment by kevinfodness** [comment]
The API ID is stored after the response comes back from the Apple News API, and is stored almost immediately, so there is a very narrow window for something to go wrong here. However, the primary case where this behavior _would_ happen is if the PHP process gives up on the remote request before it concludes. That can happen if you're not using the remote images setting (we _strongly_ encourage using remote images) and the request takes too long due to the size of the bundled images.
