### ISSUE TITLE
Articles Don't Work With Newest Version

### ISSUE THREAD

**Issue by AlexLamond** [alleyinteractive/apple-news#99]
Downloaded Apple News Preview application https://developer.apple.com/news-preview/ and articles that have published fine to Apple News throw an error when I try and preview them in the application, generally it is to do with images "Unable to determine mime-type of URL [bundle://*imagename*]". Also get a warning that the articles were created in V0.10 and a newer version 1.1.0 is available.

**Comment by markbattistella** [comment]
I am getting this same error, and it started after I activated the plugin, deactivated, renewed my API (because the plugin didn't save it), and tried to publish and preview again.

**Comment by bcampeau** [comment]
Version 0.10 is compatible with the latest News Preview tool, though it will throw a warning. We're releasing a new version of the plugin soon that will bump the version to 1.1.

Due to limitations with certain web hosts, the plugin only exports the JSON file and not the associated images. It's likely that you're dragging the JSON into the News Preview tool without the images. If you download those from WordPress and bundle them manually (i.e. place them into a folder with the JSON file) and drag that into News Preview, it should work fine.

**Comment by markbattistella** [comment]
That was a separate warning all together in my console. After I downloaded the images and had them all in the same folder the error of the versio still came up. I manually changed it and worked fine.

**Comment by bcampeau** [comment]
Great. We'll be incrementing the version number very soon in the plugin.

**Comment by bcampeau** [comment]
Although this won't be officially released to WordPress.org and WP VIP for a bit longer, if you pull the latest `master` branch from github right now, the plugin has been updated to produce version 1.1 Apple News format.

This was fixed by #107
