### ISSUE TITLE
Error with the Apple News API : NOT_FOUND (keypath articleId)

### ISSUE THREAD

**Issue by Prathimareddy23** [alleyinteractive/apple-news#992]
When we are trying to publish a revision post for an existing published post getting this error. 

Can anyone suggest  when will we get this error ? Or do we have any other settings for this one.

![image](https://user-images.githubusercontent.com/49721509/217460236-0b4f5c35-2027-4e89-b762-bc2d25788d02.png)

**Comment by kevinfodness** [comment]
Is this a standard revision to a published post (edit published post, make changes, hit Update)? Or are you using a plugin to help with the workflow?

The specific error you are getting is that there is a reference to an article ID on your Apple News channel that no longer exists on the channel. If you're using a workflow plugin, it's possible that it's deleting the original article, which is triggering a `DELETE` request to the Apple News API, and then the update doesn't work because the article has been deleted.

**Comment by Prathimareddy23** [comment]
@kevinfodness , Yes we are using the third party plugin for doing the revisionize from - https://wordpress.org/plugins/revisionize/

Also when we do revisionize for an original post , Our code base will delete the new revision post and that post content gets updated in original post.

**Comment by kevinfodness** [comment]
OK, it's likely that the third party plugin is also copying the Apple News metadata, which is triggering the delete when the copy is deleted as I alluded to above. We are shipping a fix for this for Yoast's Duplicate Post plugin in the upcoming v2.4.0: https://github.com/alleyinteractive/apple-news/pull/982/files

Unfortunately, we can't support every 3rd party plugin available. Revisionize doesn't have a filter like Yoast does, but it does have an action called `revisionize_after_create_revision` for which the second parameter in the action hook callback is the post ID of the copy that it created, which you can hook into to remove Apple News metadata from the revision. You'll want to remove all metadata starting with `apple_news_` similar to the approach in the filter above. You'll have to test this out with Revisionize to see if it works the way you expect.

**Comment by ashwinness** [comment]
This is awesome @kevinfodness . I manually deleted the keys for apple after the revisionize and it worked. I am going to try this via adding the code and will update.

**Comment by Prathimareddy23** [comment]
@kevinfodness , When we manually deleted the keys from revision piece before publish, it got worked. But when I tried adding this hook `revisionize_after_create_revision` via code level, It not worked.

First when I create new post, I'm seeing that custom fields of apple news are setting the values.

![image](https://user-images.githubusercontent.com/49721509/218121657-5cf22368-09bb-41ad-a125-4a3b1f4188de.png)

When I click on Revisionize for published post, I'm not seeing the custom fields values for apple news. When I click on publish its getting an error that it is a duplicate article ID.

![image](https://user-images.githubusercontent.com/49721509/218122167-fd949490-8363-46fb-b49b-1dc24a2a7795.png)

**Comment by Prathimareddy23** [comment]
@kevinfodness , We tried deleting the meta on new revision post, it gets published. But this is creates a duplicate post entry for the same post in apple news  publisher account. Due to this now we have two URLs pointing to the same post.

But I observed that both post has different `apple_news_api_share_url` in that publisher account. Also new ` apple_news_api_share_url`  URL  is updated for original post.

![image](https://user-images.githubusercontent.com/49721509/218512977-3c9964c5-4339-4598-b62a-0f3c0bc72103.png)

**Comment by kevinfodness** [comment]
Yeah, it's creating a new post because the API ID isn't present and it thinks it should be published anew. I'm not certain exactly how the plugin you're using works, so you may need to adjust the workflow to something like this:

- Instead of deleting the postmeta from the copy of the article, delete it from the original article.
- When the plugin replaces the original article, it might apply the postmeta to it and register it as an update instead of as a new article (this requires testing to prove out).
- You may also need to short-circuit the article deletion when the copy is deleted, such as by deleting the postmeta on the copy of the article before the article is actually deleted.

In any case, you're likely going to need to either dig into the source code of the Revisionize plugin to figure out exactly what it's doing, or just try a few approaches to see what gives you the right behavior (update instead of new publish, don't delete when the copy is deleted).

**Comment by Prathimareddy23** [comment]
@kevinfodness , Yes, I tried deleting the postmeta from original article before publishing the revision post. All meta fields are getting updated in original post once after publish , But we are getting the same error `NOT_FOUND ( KeyPath articleId)`.

I will take a look the source code of Revisionize plugin, If something I get,  I will keep posted here.
