### ISSUE TITLE
Formatting a recirc block within the body correctly 

### ISSUE THREAD

**Issue by kujain** [alleyinteractive/apple-news#994]
I have a block that displayed 3 related stories to the main article. This is usually embedded within the content and hence it needs to be placed there. I am using `apple_news_exporter_content_pre` filter to go through the blocks and conditionally build the correct AN component structure as needed. This has worked before for me for other custom blocks like sliders etc.
![image](https://user-images.githubusercontent.com/120631/222496000-f594868c-5295-483e-b89d-6299ba96f7d4.png)

But I am not sure WHICH component to build the above content as. Assuming that the **[aside](https://developer.apple.com/documentation/apple_news/aside)** component is the most appropriate, could you possibly guide me regarding the correct structure for this component to include the following:
- link title
- link image (url and caption)
- link url
- repeats the above 3X.

Thanks very much!

plugin version: Version 2.3.3
WP version: 5.9.4

**Comment by kujain** [comment]
I am probably confused as the above hook `apple_news_exporter_content_pre`  allows me to filter the html, not JSON (for which I should be using `apple_news_generate_json`!

If I use json filter, then I would need to follow AN's component structure, but as per above, I am not clear which one to use.
If I use the content_pre filter, I should be able to format the content in a way that the plugin will render it correctly. Currently the above recirc block is rendering as just a list of images, without any of the links and titles and I am not sure how to change the markup so it can be rendered by the plugin's JSON outputter in the correct way:
```
            {
               "role":"heading3",
               "text":"More Like This",
               "format":"html",
               "textStyle":"default-heading-3",
               "layout":"heading-layout"
            },
            {
               "role":"photo",
               "URL":"...../ebay_gifts_header_1500x800-1200x640.jpeg",
               "layout":"full-width-image"
            },
            {
               "role":"photo",
               "URL":"..../Jamaal-800x800.jpg",
               "layout":"full-width-image"
            },
```
I think I should be using the `apple_news_exporter_content_pre` filter to reformat the html markup so it can be recognized by the plugin's built in JSON generator (since if I wait until the json is already generated, I would not know which component to re-format, as per the above sample output!)  Thanks so much!

**Comment by kevinfodness** [comment]
Because what you're trying to do here is pretty custom, the default parsing of the plugin likely won't do what you need it to do, so I would recommend using a placeholder approach.

First, use the `apple_news_exporter_content_pre` filter and replace the recirc block with a placeholder. This can be done in one of two ways - either just put in a paragraph with a generic identifier that can be picked up later and replaced, or you can put in an identifier with some additional information that's necessary for what needs to be built later, like post IDs for recirc. For example, replace the block output with something like:

```html
<p>RECIRC_MODULE_GOES_HERE</p>
```

Then, using the `apple_news_generate_json` filter, loop through components until you find one that's a paragraph that contains that placeholder content, and replace it with your custom recirc component. That will let you write whatever custom JSON you want, and you'd only be limited by what Apple News Format allows you to do. You can test your output in News Preview and just edit the JSON file directly until you get it the way you want it, then update your filter function to write the JSON in the format that you settled on.
